-- Baseline schema for a genuinely empty Postgres volume.
--
-- Every other file in this directory is an incremental ALTER TABLE/ADD
-- COLUMN migration that assumes its base tables already exist — true until
-- now only via TypeORM's dev-mode `synchronize: true`. This file creates
-- every TypeORM-entity-backed table from scratch, generated by running the
-- real API once with synchronize enabled against an empty database and
-- dumping the resulting schema — not hand-written — so it exactly matches
-- current entity definitions. Runs first (00000000 sorts before every other
-- migration's date prefix), so a fresh server no longer needs a manual
-- bootstrap step before `api` can start.
--
-- Tables with no TypeORM @Entity() class (e.g. qa_service_status_incidents)
-- are intentionally absent here — those are still created by their own
-- incremental migration further down the chain.

BEGIN;

--
-- Name: uuid-ossp; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA public;


--
-- Name: EXTENSION "uuid-ossp"; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON EXTENSION "uuid-ossp" IS 'generate universally unique identifiers (UUIDs)';


--
-- Name: vector; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS vector WITH SCHEMA public;


--
-- Name: EXTENSION vector; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON EXTENSION vector IS 'vector data type and ivfflat and hnsw access methods';


-- cosine_similarity() is NOT dumped here — it's infra set up by
-- init-db/01-init.sql (which also creates the vector extension above, via
-- Postgres' own docker-entrypoint-initdb.d, before this file ever runs),
-- not a TypeORM-entity-backed object. Redefining it here would collide with
-- that earlier CREATE FUNCTION (no OR REPLACE in a plain pg_dump).

SET default_table_access_method = heap;

--
-- Name: agent_sessions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.agent_sessions (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    "agentType" character varying(10) NOT NULL,
    status character varying(20) DEFAULT 'idle'::character varying NOT NULL,
    messages jsonb DEFAULT '[]'::jsonb NOT NULL,
    context jsonb DEFAULT '{}'::jsonb NOT NULL,
    metadata jsonb,
    "createdAt" timestamp without time zone DEFAULT now() NOT NULL,
    "updatedAt" timestamp without time zone DEFAULT now() NOT NULL
);


--
-- Name: agent_tasks; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.agent_tasks (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    title character varying NOT NULL,
    description text,
    "agentType" character varying(10) NOT NULL,
    status character varying(20) DEFAULT 'todo'::character varying NOT NULL,
    priority character varying(10) DEFAULT 'medium'::character varying NOT NULL,
    labels text DEFAULT ''::text NOT NULL,
    "sessionId" uuid,
    result jsonb,
    metadata jsonb,
    "blockedReason" text,
    "startedAt" timestamp without time zone,
    "completedAt" timestamp without time zone,
    "createdAt" timestamp without time zone DEFAULT now() NOT NULL,
    "updatedAt" timestamp without time zone DEFAULT now() NOT NULL
);


--
-- Name: business_items; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.business_items (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    type character varying(50) NOT NULL,
    name character varying NOT NULL,
    description text,
    content jsonb,
    confidence character varying(20) DEFAULT 'inferred'::character varying NOT NULL,
    "verificationStatus" character varying(20) DEFAULT 'unverified'::character varying NOT NULL,
    tags text DEFAULT ''::text NOT NULL,
    metadata jsonb,
    "sourceId" uuid,
    "documentId" uuid,
    "externalId" character varying,
    "createdAt" timestamp without time zone DEFAULT now() NOT NULL,
    "updatedAt" timestamp without time zone DEFAULT now() NOT NULL
);


--
-- Name: business_relationships; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.business_relationships (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    type character varying(50) NOT NULL,
    "fromItemId" uuid NOT NULL,
    "toItemId" uuid NOT NULL,
    description text,
    metadata jsonb,
    "createdAt" timestamp without time zone DEFAULT now() NOT NULL
);


--
-- Name: chat_agent_memories; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.chat_agent_memories (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    "projectId" uuid NOT NULL,
    "agentId" uuid NOT NULL,
    category character varying(20) NOT NULL,
    content text NOT NULL,
    "contentHash" character varying(64) NOT NULL,
    status character varying(10) DEFAULT 'active'::character varying NOT NULL,
    importance smallint DEFAULT '3'::smallint NOT NULL,
    "createdBy" uuid NOT NULL,
    "updatedBy" uuid NOT NULL,
    version integer DEFAULT 1 NOT NULL,
    "expiresAt" timestamp with time zone,
    "lastUsedAt" timestamp with time zone,
    "createdAt" timestamp with time zone DEFAULT now() NOT NULL,
    "updatedAt" timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: chat_agent_memory_revisions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.chat_agent_memory_revisions (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    "projectId" uuid NOT NULL,
    "memoryId" uuid NOT NULL,
    version integer NOT NULL,
    change character varying(12) NOT NULL,
    category character varying(20) NOT NULL,
    content text NOT NULL,
    importance smallint NOT NULL,
    "actorId" uuid NOT NULL,
    "createdAt" timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: chat_agent_prompt_installs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.chat_agent_prompt_installs (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    "projectId" uuid NOT NULL,
    "agentId" uuid NOT NULL,
    scenario character varying(20) NOT NULL,
    "promptId" uuid NOT NULL,
    "updatedAt" timestamp without time zone DEFAULT now() NOT NULL
);


--
-- Name: chat_agents; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.chat_agents (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    "projectId" uuid NOT NULL,
    kind character varying,
    name character varying NOT NULL,
    avatar character varying(20),
    "modelSelection" jsonb,
    "maxIterations" integer,
    temperature real,
    email character varying NOT NULL,
    aliases jsonb DEFAULT '[]'::jsonb NOT NULL,
    instructions text DEFAULT ''::text NOT NULL,
    enabled boolean DEFAULT true NOT NULL,
    "createdAt" timestamp without time zone DEFAULT now() NOT NULL,
    CONSTRAINT chat_agents_supported_kind CHECK (((kind IS NULL) OR ((kind)::text = ANY ((ARRAY['qae'::character varying, 'aue'::character varying, 'superqa'::character varying])::text[]))))
);


--
-- Name: chat_channels; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.chat_channels (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    "installationId" uuid NOT NULL,
    "externalId" character varying NOT NULL,
    name character varying NOT NULL,
    "createdAt" timestamp without time zone DEFAULT now() NOT NULL
);


--
-- Name: chat_conversations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.chat_conversations (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    "projectId" uuid NOT NULL,
    kind character varying NOT NULL,
    title character varying NOT NULL,
    "createdBy" uuid NOT NULL,
    "memberIds" jsonb NOT NULL,
    "agentId" uuid,
    "agentIds" jsonb DEFAULT '[]'::jsonb NOT NULL,
    instructions text DEFAULT ''::text NOT NULL,
    "agentInstructions" jsonb DEFAULT '{}'::jsonb NOT NULL,
    "policyVersion" integer DEFAULT 1 NOT NULL,
    "dedupKey" character varying,
    "installationId" uuid,
    "externalId" character varying,
    archived boolean DEFAULT false NOT NULL,
    "createdAt" timestamp without time zone DEFAULT now() NOT NULL,
    "updatedAt" timestamp without time zone DEFAULT now() NOT NULL
);


--
-- Name: chat_deliveries; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.chat_deliveries (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    "installationId" uuid NOT NULL,
    "messageId" uuid NOT NULL,
    address jsonb NOT NULL,
    status character varying DEFAULT 'waiting'::character varying NOT NULL,
    "externalId" character varying,
    "startedAt" timestamp with time zone,
    "createdAt" timestamp without time zone DEFAULT now() NOT NULL
);


--
-- Name: chat_installations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.chat_installations (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    "projectId" uuid NOT NULL,
    "agentId" uuid,
    "agentIds" jsonb DEFAULT '[]'::jsonb NOT NULL,
    provider character varying NOT NULL,
    "accessMode" character varying(20) DEFAULT 'read_reply'::character varying NOT NULL,
    "providerId" character varying NOT NULL,
    name character varying NOT NULL,
    "botId" character varying NOT NULL,
    secret character varying NOT NULL,
    enabled boolean DEFAULT true NOT NULL,
    "createdAt" timestamp without time zone DEFAULT now() NOT NULL
);


--
-- Name: chat_meeting_activity; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.chat_meeting_activity (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    sequence integer NOT NULL,
    "meetingId" uuid NOT NULL,
    "projectId" uuid NOT NULL,
    kind character varying NOT NULL,
    "authorId" uuid,
    "authorKind" character varying,
    "authorName" character varying,
    text text,
    "replyToId" uuid,
    "requestId" uuid,
    "createdAt" timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: chat_meeting_activity_sequence_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.chat_meeting_activity_sequence_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: chat_meeting_activity_sequence_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.chat_meeting_activity_sequence_seq OWNED BY public.chat_meeting_activity.sequence;


--
-- Name: chat_meeting_entries; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.chat_meeting_entries (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    sequence integer NOT NULL,
    "meetingId" uuid NOT NULL,
    "eventId" character varying NOT NULL,
    speaker character varying NOT NULL,
    source character varying NOT NULL,
    text text NOT NULL,
    "createdAt" timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: chat_meeting_entries_sequence_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.chat_meeting_entries_sequence_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: chat_meeting_entries_sequence_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.chat_meeting_entries_sequence_seq OWNED BY public.chat_meeting_entries.sequence;


--
-- Name: chat_meeting_peers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.chat_meeting_peers (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    "meetingId" uuid NOT NULL,
    "memberId" uuid NOT NULL,
    name character varying NOT NULL,
    "sessionId" uuid NOT NULL,
    "seenAt" timestamp with time zone NOT NULL,
    "consentAt" timestamp with time zone NOT NULL
);


--
-- Name: chat_meeting_runs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.chat_meeting_runs (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    "meetingId" uuid NOT NULL,
    "projectId" uuid NOT NULL,
    "requestId" character varying NOT NULL,
    "memberId" uuid NOT NULL,
    "keyId" uuid NOT NULL,
    kind character varying NOT NULL,
    prompt text DEFAULT ''::text NOT NULL,
    "requireRelevance" boolean DEFAULT false NOT NULL,
    status character varying DEFAULT 'queued'::character varying NOT NULL,
    version integer NOT NULL,
    "policyVersion" integer NOT NULL,
    "throughSequence" integer NOT NULL,
    "evidenceIds" jsonb DEFAULT '[]'::jsonb NOT NULL,
    result jsonb,
    usage jsonb,
    error character varying,
    delivery character varying,
    "publishedMessageId" uuid,
    "voiceAt" timestamp with time zone,
    "startedAt" timestamp with time zone,
    "createdAt" timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: chat_meeting_signals; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.chat_meeting_signals (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    sequence integer NOT NULL,
    "meetingId" uuid NOT NULL,
    "requestId" uuid NOT NULL,
    sender uuid NOT NULL,
    recipient uuid NOT NULL,
    payload jsonb NOT NULL,
    "createdAt" timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: chat_meeting_signals_sequence_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.chat_meeting_signals_sequence_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: chat_meeting_signals_sequence_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.chat_meeting_signals_sequence_seq OWNED BY public.chat_meeting_signals.sequence;


--
-- Name: chat_meeting_voice; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.chat_meeting_voice (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    "meetingId" uuid NOT NULL,
    "agentId" uuid NOT NULL,
    "projectId" uuid NOT NULL,
    "peerSession" uuid,
    capability character varying,
    "providerId" character varying,
    "openAIVoice" character varying DEFAULT 'marin'::character varying NOT NULL,
    status character varying DEFAULT 'pending'::character varying NOT NULL,
    stopped boolean DEFAULT false NOT NULL,
    finalized boolean DEFAULT false NOT NULL,
    seconds double precision DEFAULT '0'::double precision NOT NULL,
    "attemptSeconds" double precision DEFAULT '0'::double precision NOT NULL,
    attempts integer DEFAULT 1 NOT NULL,
    "policyVersion" integer DEFAULT 1 NOT NULL,
    "controlAt" timestamp with time zone NOT NULL,
    error character varying,
    "seenAt" timestamp with time zone NOT NULL,
    "expiresAt" timestamp with time zone NOT NULL,
    "createdAt" timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: chat_meetings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.chat_meetings (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    "projectId" uuid NOT NULL,
    "conversationId" uuid NOT NULL,
    "createdBy" uuid NOT NULL,
    "keyId" uuid NOT NULL,
    "requestId" uuid NOT NULL,
    "agentId" uuid NOT NULL,
    title character varying DEFAULT 'Meeting'::character varying NOT NULL,
    "scheduledStart" timestamp with time zone,
    "scheduledEnd" timestamp with time zone,
    attendees jsonb DEFAULT '[]'::jsonb NOT NULL,
    "participantMemberIds" jsonb DEFAULT '[]'::jsonb NOT NULL,
    "agentParticipants" jsonb DEFAULT '[]'::jsonb NOT NULL,
    "shareTranscriptWithAgents" boolean DEFAULT true NOT NULL,
    mode character varying NOT NULL,
    "liveVoice" boolean DEFAULT false NOT NULL,
    provider character varying NOT NULL,
    url text,
    status character varying DEFAULT 'live'::character varying NOT NULL,
    "botId" character varying,
    error character varying,
    version integer DEFAULT 1 NOT NULL,
    stopped boolean DEFAULT false NOT NULL,
    "syncedAt" timestamp with time zone,
    "liveAt" timestamp with time zone,
    "createdAt" timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: chat_messages; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.chat_messages (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    sequence integer NOT NULL,
    "projectId" uuid NOT NULL,
    "conversationId" uuid NOT NULL,
    "requestId" character varying NOT NULL,
    "authorId" character varying NOT NULL,
    "authorName" character varying NOT NULL,
    "authorKind" character varying NOT NULL,
    text text NOT NULL,
    content jsonb,
    "replyToId" uuid,
    "meetingContextId" uuid,
    status character varying DEFAULT 'sent'::character varying NOT NULL,
    error character varying,
    "externalThreadId" character varying,
    "createdAt" timestamp without time zone DEFAULT now() NOT NULL
);


--
-- Name: chat_messages_sequence_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.chat_messages_sequence_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: chat_messages_sequence_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.chat_messages_sequence_seq OWNED BY public.chat_messages.sequence;


--
-- Name: chat_prompts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.chat_prompts (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    "projectId" uuid NOT NULL,
    name character varying(60) NOT NULL,
    content text NOT NULL,
    "createdBy" uuid,
    "updatedBy" uuid,
    "createdAt" timestamp without time zone DEFAULT now() NOT NULL,
    "updatedAt" timestamp without time zone DEFAULT now() NOT NULL
);


--
-- Name: chat_tasks; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.chat_tasks (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    "projectId" uuid NOT NULL,
    "conversationId" uuid NOT NULL,
    "messageId" uuid NOT NULL,
    title character varying NOT NULL,
    description text NOT NULL,
    "createdBy" character varying NOT NULL,
    status character varying DEFAULT 'open'::character varying NOT NULL,
    "createdAt" timestamp without time zone DEFAULT now() NOT NULL
);


--
-- Name: chat_work; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.chat_work (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    "projectId" uuid NOT NULL,
    "conversationId" uuid NOT NULL,
    "agentId" uuid NOT NULL,
    "messageId" uuid NOT NULL,
    "responseId" uuid NOT NULL,
    status character varying DEFAULT 'queued'::character varying NOT NULL,
    "leaseToken" uuid,
    "leaseUntil" timestamp with time zone,
    "policyVersion" integer NOT NULL,
    "requireRelevance" boolean DEFAULT false NOT NULL,
    usage jsonb,
    "createdAt" timestamp without time zone DEFAULT now() NOT NULL
);


--
-- Name: chunks; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.chunks (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    document_id uuid NOT NULL,
    content text NOT NULL,
    "chunkIndex" integer NOT NULL,
    metadata jsonb,
    "createdAt" timestamp without time zone DEFAULT now() NOT NULL,
    embedding jsonb
);


--
-- Name: documents; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.documents (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    source_id uuid NOT NULL,
    "externalId" character varying NOT NULL,
    type character varying(50) NOT NULL,
    title character varying NOT NULL,
    content text NOT NULL,
    url character varying,
    metadata jsonb,
    "contentHash" character varying NOT NULL,
    "processedHash" character varying,
    "createdAt" timestamp without time zone DEFAULT now() NOT NULL,
    "updatedAt" timestamp without time zone DEFAULT now() NOT NULL
);


--
-- Name: environments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.environments (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    name character varying(100) NOT NULL,
    description text,
    color character varying(20) DEFAULT '#3B82F6'::character varying NOT NULL,
    variables jsonb DEFAULT '[]'::jsonb NOT NULL,
    "baseUrl" character varying,
    "isDefault" boolean DEFAULT false NOT NULL,
    "maxRetries" smallint,
    "retryDelayMs" integer,
    "createdAt" timestamp without time zone DEFAULT now() NOT NULL,
    "updatedAt" timestamp without time zone DEFAULT now() NOT NULL
);


--
-- Name: harness_executions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.harness_executions (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    "requestId" uuid NOT NULL,
    "requestHash" character varying NOT NULL,
    "proposalRunId" uuid NOT NULL,
    "targetId" character varying NOT NULL,
    "targetHash" character varying NOT NULL,
    actor character varying NOT NULL,
    steps jsonb NOT NULL,
    "retryOf" uuid,
    status character varying DEFAULT 'queued'::character varying NOT NULL,
    reason character varying DEFAULT ''::character varying NOT NULL,
    token uuid,
    "leaseUntil" timestamp with time zone,
    deadline timestamp with time zone NOT NULL,
    report jsonb,
    screenshot text,
    "artifactHash" character varying,
    "completionHash" character varying,
    flaky boolean DEFAULT false NOT NULL,
    "createdAt" timestamp without time zone DEFAULT now() NOT NULL
);


--
-- Name: harness_runs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.harness_runs (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    "requestId" uuid NOT NULL,
    "requestHash" character varying NOT NULL,
    task jsonb NOT NULL,
    evidence jsonb NOT NULL,
    "caseSnapshot" jsonb,
    profile jsonb NOT NULL,
    prompt text NOT NULL,
    status character varying DEFAULT 'queued'::character varying NOT NULL,
    reason character varying DEFAULT ''::character varying NOT NULL,
    attempts jsonb DEFAULT '[]'::jsonb NOT NULL,
    proposal jsonb,
    review jsonb,
    deadline timestamp with time zone NOT NULL,
    "leaseUntil" timestamp with time zone,
    "createdAt" timestamp without time zone DEFAULT now() NOT NULL
);


--
-- Name: outpost_activities; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.outpost_activities (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    "projectId" uuid NOT NULL,
    "agentId" uuid NOT NULL,
    key character varying NOT NULL,
    source character varying DEFAULT 'built_in'::character varying NOT NULL,
    name character varying NOT NULL,
    description text DEFAULT ''::text NOT NULL,
    skill character varying NOT NULL,
    inputs jsonb DEFAULT '{}'::jsonb NOT NULL,
    instructions text,
    triggers jsonb DEFAULT '[]'::jsonb NOT NULL,
    "autonomyLevel" character varying DEFAULT 'observer'::character varying NOT NULL,
    enabled boolean DEFAULT true NOT NULL,
    "createdBy" uuid,
    "createdAt" timestamp without time zone DEFAULT now() NOT NULL,
    "updatedAt" timestamp without time zone DEFAULT now() NOT NULL
);


--
-- Name: outpost_runs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.outpost_runs (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    "projectId" uuid NOT NULL,
    "activityId" uuid NOT NULL,
    "requestId" uuid NOT NULL,
    "triggeredBy" character varying NOT NULL,
    status character varying DEFAULT 'queued'::character varying NOT NULL,
    "autonomyLevel" character varying NOT NULL,
    "resultSummary" text,
    "artifactRequestId" uuid,
    "chatMessageId" uuid,
    "sessionId" uuid,
    "approvalStatus" character varying DEFAULT 'not_required'::character varying NOT NULL,
    error text,
    "startedAt" timestamp with time zone,
    "finishedAt" timestamp with time zone,
    "createdAt" timestamp without time zone DEFAULT now() NOT NULL
);


--
-- Name: qa_audit_events; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.qa_audit_events (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    "projectId" uuid NOT NULL,
    actor character varying NOT NULL,
    action character varying NOT NULL,
    data jsonb DEFAULT '{}'::jsonb NOT NULL,
    "createdAt" timestamp without time zone DEFAULT now() NOT NULL
);


--
-- Name: qa_auth_sessions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.qa_auth_sessions (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    "memberId" uuid,
    "superAdminId" uuid,
    "impersonatedBySuperAdminId" uuid,
    "tokenDigest" character varying NOT NULL,
    "expiresAt" timestamp with time zone NOT NULL,
    "revokedAt" timestamp with time zone,
    "createdAt" timestamp without time zone DEFAULT now() NOT NULL
);


--
-- Name: qa_autonomous_runs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.qa_autonomous_runs (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    "projectId" uuid NOT NULL,
    "requestId" uuid NOT NULL,
    "suiteId" uuid NOT NULL,
    snapshot jsonb NOT NULL,
    status character varying DEFAULT 'queued'::character varying NOT NULL,
    token uuid,
    "workerKeyId" uuid,
    deadline timestamp with time zone NOT NULL,
    "browserExecutions" jsonb DEFAULT '{}'::jsonb NOT NULL,
    results jsonb,
    "completionHash" character varying,
    dataset jsonb,
    "cleanupReceipt" jsonb,
    "repairPatch" jsonb,
    "createdAt" timestamp without time zone DEFAULT now() NOT NULL
);


--
-- Name: qa_autonomous_suites; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.qa_autonomous_suites (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    "projectId" uuid NOT NULL,
    name character varying NOT NULL,
    version integer DEFAULT 1 NOT NULL,
    "previousId" uuid,
    checks jsonb NOT NULL,
    "manifestHash" character varying NOT NULL,
    "approvedBy" uuid,
    "createdAt" timestamp without time zone DEFAULT now() NOT NULL
);


--
-- Name: qa_benchmarks; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.qa_benchmarks (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    "projectId" uuid NOT NULL,
    "requestId" uuid NOT NULL,
    corpus jsonb NOT NULL,
    "corpusHash" character varying NOT NULL,
    "approvedBy" uuid,
    paused boolean DEFAULT true NOT NULL,
    "runIds" jsonb DEFAULT '[]'::jsonb NOT NULL,
    "createdAt" timestamp without time zone DEFAULT now() NOT NULL
);


--
-- Name: qa_execution_plans; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.qa_execution_plans (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    name text NOT NULL,
    description text DEFAULT ''::text NOT NULL,
    "testIds" jsonb DEFAULT '[]'::jsonb NOT NULL,
    environment character varying DEFAULT 'manual'::character varying NOT NULL,
    browser character varying DEFAULT 'manual'::character varying NOT NULL,
    "createdAt" timestamp without time zone DEFAULT now() NOT NULL,
    "updatedAt" timestamp without time zone DEFAULT now() NOT NULL
);


--
-- Name: qa_executions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.qa_executions (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    "runId" uuid NOT NULL,
    "testId" uuid NOT NULL,
    snapshot jsonb NOT NULL,
    status character varying DEFAULT 'pending'::character varying NOT NULL,
    result jsonb,
    "completedAt" timestamp with time zone,
    "agentRunId" character varying,
    "createdAt" timestamp without time zone DEFAULT now() NOT NULL
);


--
-- Name: qa_generation_runs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.qa_generation_runs (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    kind character varying NOT NULL,
    status character varying DEFAULT 'pending'::character varying NOT NULL,
    label character varying NOT NULL,
    input jsonb NOT NULL,
    result jsonb,
    error text,
    applied boolean DEFAULT false NOT NULL,
    "createdAt" timestamp without time zone DEFAULT now() NOT NULL,
    "updatedAt" timestamp without time zone DEFAULT now() NOT NULL
);


--
-- Name: qa_healing_suggestions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.qa_healing_suggestions (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    issue text NOT NULL,
    "affectedTests" jsonb NOT NULL,
    "currentLocator" text NOT NULL,
    "suggestedLocator" text NOT NULL,
    "rootCause" character varying DEFAULT ''::character varying NOT NULL,
    owner character varying DEFAULT ''::character varying NOT NULL,
    status character varying DEFAULT 'pending'::character varying NOT NULL,
    "reviewedBy" character varying,
    "createdAt" timestamp without time zone DEFAULT now() NOT NULL
);


--
-- Name: qa_oidc_attempts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.qa_oidc_attempts (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    "stateDigest" character varying NOT NULL,
    nonce character varying NOT NULL,
    verifier character varying NOT NULL,
    "expiresAt" timestamp with time zone NOT NULL,
    "createdAt" timestamp without time zone DEFAULT now() NOT NULL
);


--
-- Name: qa_org_invitations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.qa_org_invitations (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    "projectId" uuid NOT NULL,
    email character varying(254) NOT NULL,
    role character varying NOT NULL,
    "tokenDigest" character varying NOT NULL,
    "expiresAt" timestamp with time zone NOT NULL,
    "acceptedAt" timestamp with time zone,
    "revokedAt" timestamp with time zone,
    "createdBy" uuid,
    "memberKeyId" uuid NOT NULL,
    "createdAt" timestamp without time zone DEFAULT now() NOT NULL
);


--
-- Name: qa_org_members; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.qa_org_members (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    "projectId" uuid NOT NULL,
    email character varying(254) NOT NULL,
    "keyId" uuid NOT NULL,
    "passwordHash" character varying,
    "tokenVersion" integer DEFAULT 0 NOT NULL,
    active boolean DEFAULT true NOT NULL,
    "createdAt" timestamp without time zone DEFAULT now() NOT NULL
);


--
-- Name: qa_org_support_settings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.qa_org_support_settings (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    "projectId" uuid NOT NULL,
    settings jsonb DEFAULT '{}'::jsonb NOT NULL,
    "createdAt" timestamp with time zone DEFAULT now() NOT NULL,
    "updatedAt" timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: qa_organizations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.qa_organizations (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    name character varying NOT NULL,
    "createdAt" timestamp without time zone DEFAULT now() NOT NULL
);


--
-- Name: qa_project_keys; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.qa_project_keys (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    "projectId" uuid NOT NULL,
    digest character varying NOT NULL,
    role character varying NOT NULL,
    label character varying NOT NULL,
    "expiresAt" timestamp with time zone NOT NULL,
    revoked boolean DEFAULT false NOT NULL
);


--
-- Name: qa_projects; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.qa_projects (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    "organizationId" uuid,
    name character varying NOT NULL,
    "workspaceId" character varying NOT NULL,
    "applicationId" character varying NOT NULL,
    environment character varying NOT NULL,
    paused boolean DEFAULT false NOT NULL,
    origins jsonb NOT NULL,
    targets jsonb NOT NULL,
    requirements jsonb NOT NULL,
    "dailyRunLimit" integer DEFAULT 20 NOT NULL,
    "onboardingCompletedAt" timestamp with time zone,
    "createdAt" timestamp without time zone DEFAULT now() NOT NULL
);


--
-- Name: qa_runs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.qa_runs (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    "requestId" uuid NOT NULL,
    "requestHash" character varying NOT NULL,
    mode character varying DEFAULT 'manual'::character varying NOT NULL,
    environment character varying NOT NULL,
    browser character varying NOT NULL,
    "createdAt" timestamp without time zone DEFAULT now() NOT NULL
);


--
-- Name: qa_super_admins; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.qa_super_admins (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    email character varying(254) NOT NULL,
    "passwordHash" character varying NOT NULL,
    active boolean DEFAULT true NOT NULL,
    "createdAt" timestamp without time zone DEFAULT now() NOT NULL
);


--
-- Name: qa_test_cases; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.qa_test_cases (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    title text NOT NULL,
    priority character varying DEFAULT 'P2'::character varying NOT NULL,
    automation character varying DEFAULT 'manual'::character varying NOT NULL,
    owner character varying DEFAULT ''::character varying NOT NULL,
    flow character varying DEFAULT ''::character varying NOT NULL,
    risk character varying,
    category character varying,
    technique character varying,
    severity character varying,
    platform character varying,
    tags jsonb DEFAULT '[]'::jsonb NOT NULL,
    steps jsonb NOT NULL,
    preconditions jsonb DEFAULT '[]'::jsonb NOT NULL,
    "baseUrl" character varying,
    "reviewStatus" character varying DEFAULT 'draft'::character varying NOT NULL,
    revision integer DEFAULT 1 NOT NULL,
    "reviewedBy" character varying,
    evidence jsonb,
    "workflowArtifactId" uuid,
    "sourceCaseId" character varying,
    "createdAt" timestamp without time zone DEFAULT now() NOT NULL,
    "updatedAt" timestamp without time zone DEFAULT now() NOT NULL
);


--
-- Name: qa_workflow_artifacts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.qa_workflow_artifacts (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    "projectId" uuid NOT NULL,
    "requestId" uuid NOT NULL,
    "agentType" character varying NOT NULL,
    skill character varying NOT NULL,
    "schemaVersion" integer DEFAULT 1 NOT NULL,
    "contentHash" character varying NOT NULL,
    "resultJson" text NOT NULL,
    status character varying NOT NULL,
    summary text NOT NULL,
    "producedAt" timestamp with time zone NOT NULL,
    "publishedAt" timestamp without time zone DEFAULT now() NOT NULL
);


--
-- Name: sources; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sources (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    name character varying NOT NULL,
    type character varying(50) NOT NULL,
    config jsonb NOT NULL,
    status character varying(50) DEFAULT 'disconnected'::character varying NOT NULL,
    "lastSync" timestamp without time zone,
    "syncMode" character varying(20) DEFAULT 'manual'::character varying NOT NULL,
    "itemsCount" integer DEFAULT 0 NOT NULL,
    "errorMessage" text,
    permissions text DEFAULT ''::text NOT NULL,
    "syncState" jsonb,
    "webhookConfig" jsonb,
    "createdAt" timestamp without time zone DEFAULT now() NOT NULL,
    "updatedAt" timestamp without time zone DEFAULT now() NOT NULL
);


--
-- Name: sync_jobs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sync_jobs (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    "pipelineVersion" integer DEFAULT 0 NOT NULL,
    request jsonb,
    "leaseToken" uuid,
    "leaseUntil" timestamp with time zone,
    attempts integer DEFAULT 0 NOT NULL,
    "nextAttemptAt" timestamp with time zone,
    source_id uuid NOT NULL,
    status character varying(20) DEFAULT 'queued'::character varying NOT NULL,
    trigger character varying(20) DEFAULT 'manual'::character varying NOT NULL,
    "currentStage" character varying(30),
    stages jsonb DEFAULT '[]'::jsonb NOT NULL,
    stats jsonb,
    "itemsProcessed" integer DEFAULT 0 NOT NULL,
    "itemsTotal" integer DEFAULT 0 NOT NULL,
    "errorMessage" text,
    metadata jsonb,
    logs jsonb DEFAULT '[]'::jsonb NOT NULL,
    "startedAt" timestamp without time zone,
    "completedAt" timestamp without time zone,
    "createdAt" timestamp without time zone DEFAULT now() NOT NULL,
    "updatedAt" timestamp without time zone DEFAULT now() NOT NULL
);


--
-- Name: sync_work; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sync_work (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    sync_job_id uuid NOT NULL,
    "externalId" character varying NOT NULL,
    "documentId" uuid NOT NULL,
    "revisionHash" character varying NOT NULL,
    snapshot jsonb NOT NULL,
    chunks jsonb,
    extraction jsonb
);


--
-- Name: chat_meeting_activity sequence; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chat_meeting_activity ALTER COLUMN sequence SET DEFAULT nextval('public.chat_meeting_activity_sequence_seq'::regclass);


--
-- Name: chat_meeting_entries sequence; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chat_meeting_entries ALTER COLUMN sequence SET DEFAULT nextval('public.chat_meeting_entries_sequence_seq'::regclass);


--
-- Name: chat_meeting_signals sequence; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chat_meeting_signals ALTER COLUMN sequence SET DEFAULT nextval('public.chat_meeting_signals_sequence_seq'::regclass);


--
-- Name: chat_messages sequence; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chat_messages ALTER COLUMN sequence SET DEFAULT nextval('public.chat_messages_sequence_seq'::regclass);


--
-- Name: qa_autonomous_runs PK_015f7eb735fef44b0cfe1f727bb; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.qa_autonomous_runs
    ADD CONSTRAINT "PK_015f7eb735fef44b0cfe1f727bb" PRIMARY KEY (id);


--
-- Name: business_items PK_04df0e9fb386a86d2e1ef2ab1c6; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.business_items
    ADD CONSTRAINT "PK_04df0e9fb386a86d2e1ef2ab1c6" PRIMARY KEY (id);


--
-- Name: agent_tasks PK_0dd9472bb57b7ab7d0a5cd1f20b; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.agent_tasks
    ADD CONSTRAINT "PK_0dd9472bb57b7ab7d0a5cd1f20b" PRIMARY KEY (id);


--
-- Name: business_relationships PK_0f99bb3ef2a1e47dcc4ee3b6ea1; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.business_relationships
    ADD CONSTRAINT "PK_0f99bb3ef2a1e47dcc4ee3b6ea1" PRIMARY KEY (id);


--
-- Name: qa_org_support_settings PK_119c0c89968628379e7b8f13576; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.qa_org_support_settings
    ADD CONSTRAINT "PK_119c0c89968628379e7b8f13576" PRIMARY KEY (id);


--
-- Name: qa_workflow_artifacts PK_1657291e30c79cc0d25618e0cfc; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.qa_workflow_artifacts
    ADD CONSTRAINT "PK_1657291e30c79cc0d25618e0cfc" PRIMARY KEY (id);


--
-- Name: qa_audit_events PK_175ae1c87bc0da080e2d79a8ac7; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.qa_audit_events
    ADD CONSTRAINT "PK_175ae1c87bc0da080e2d79a8ac7" PRIMARY KEY (id);


--
-- Name: chat_meeting_runs PK_1ce0cd6b638c3a5503fe69b04a4; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chat_meeting_runs
    ADD CONSTRAINT "PK_1ce0cd6b638c3a5503fe69b04a4" PRIMARY KEY (id);


--
-- Name: chat_tasks PK_1de83bd4d4eec885090c5ce75c4; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chat_tasks
    ADD CONSTRAINT "PK_1de83bd4d4eec885090c5ce75c4" PRIMARY KEY (id);


--
-- Name: qa_org_invitations PK_2195121650bb78f81b4f5829839; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.qa_org_invitations
    ADD CONSTRAINT "PK_2195121650bb78f81b4f5829839" PRIMARY KEY (id);


--
-- Name: qa_test_cases PK_225eadd71f20078984caa4c5b55; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.qa_test_cases
    ADD CONSTRAINT "PK_225eadd71f20078984caa4c5b55" PRIMARY KEY (id);


--
-- Name: qa_autonomous_suites PK_2313e09560e154e06f621330e0c; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.qa_autonomous_suites
    ADD CONSTRAINT "PK_2313e09560e154e06f621330e0c" PRIMARY KEY (id);


--
-- Name: qa_org_members PK_28d3e77ed8a4a5206eca1353e70; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.qa_org_members
    ADD CONSTRAINT "PK_28d3e77ed8a4a5206eca1353e70" PRIMARY KEY (id);


--
-- Name: chat_prompts PK_2a064a6725a7d746bcbca88b5cb; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chat_prompts
    ADD CONSTRAINT "PK_2a064a6725a7d746bcbca88b5cb" PRIMARY KEY (id);


--
-- Name: chat_agents PK_34080b7ccf51b01064d0615b531; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chat_agents
    ADD CONSTRAINT "PK_34080b7ccf51b01064d0615b531" PRIMARY KEY (id);


--
-- Name: qa_generation_runs PK_36e25e231d60e815b6fb98288b0; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.qa_generation_runs
    ADD CONSTRAINT "PK_36e25e231d60e815b6fb98288b0" PRIMARY KEY (id);


--
-- Name: chat_messages PK_40c55ee0e571e268b0d3cd37d10; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chat_messages
    ADD CONSTRAINT "PK_40c55ee0e571e268b0d3cd37d10" PRIMARY KEY (id);


--
-- Name: chat_deliveries PK_45e8784c6916581ea3e3197c54c; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chat_deliveries
    ADD CONSTRAINT "PK_45e8784c6916581ea3e3197c54c" PRIMARY KEY (id);


--
-- Name: qa_super_admins PK_50dc0a495aa27891de6cab0376f; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.qa_super_admins
    ADD CONSTRAINT "PK_50dc0a495aa27891de6cab0376f" PRIMARY KEY (id);


--
-- Name: agent_sessions PK_56f9e856ca24a6064c903044605; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.agent_sessions
    ADD CONSTRAINT "PK_56f9e856ca24a6064c903044605" PRIMARY KEY (id);


--
-- Name: chat_meeting_entries PK_591a1764e39fb6003dad142b406; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chat_meeting_entries
    ADD CONSTRAINT "PK_591a1764e39fb6003dad142b406" PRIMARY KEY (id);


--
-- Name: chat_meeting_signals PK_5fbfd8d74e77aa67d44ebb5d4be; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chat_meeting_signals
    ADD CONSTRAINT "PK_5fbfd8d74e77aa67d44ebb5d4be" PRIMARY KEY (id);


--
-- Name: qa_auth_sessions PK_624325a2624151528862d689dac; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.qa_auth_sessions
    ADD CONSTRAINT "PK_624325a2624151528862d689dac" PRIMARY KEY (id);


--
-- Name: outpost_activities PK_64bcd6e4316dde7339822ef5b71; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.outpost_activities
    ADD CONSTRAINT "PK_64bcd6e4316dde7339822ef5b71" PRIMARY KEY (id);


--
-- Name: chat_installations PK_6604b66634496b3e2fa7c9a71f5; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chat_installations
    ADD CONSTRAINT "PK_6604b66634496b3e2fa7c9a71f5" PRIMARY KEY (id);


--
-- Name: chat_agent_prompt_installs PK_743a2b9a46e5cb93c4c9cc97d11; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chat_agent_prompt_installs
    ADD CONSTRAINT "PK_743a2b9a46e5cb93c4c9cc97d11" PRIMARY KEY (id);


--
-- Name: chat_agent_memory_revisions PK_75e246d20d005b6fd1422141038; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chat_agent_memory_revisions
    ADD CONSTRAINT "PK_75e246d20d005b6fd1422141038" PRIMARY KEY (id);


--
-- Name: qa_oidc_attempts PK_790d2991ceb1283fd4955c80589; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.qa_oidc_attempts
    ADD CONSTRAINT "PK_790d2991ceb1283fd4955c80589" PRIMARY KEY (id);


--
-- Name: chat_meetings PK_804551f5696b273b5731fcaeade; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chat_meetings
    ADD CONSTRAINT "PK_804551f5696b273b5731fcaeade" PRIMARY KEY (id);


--
-- Name: sources PK_85523beafe5a2a6b90b02096443; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sources
    ADD CONSTRAINT "PK_85523beafe5a2a6b90b02096443" PRIMARY KEY (id);


--
-- Name: sync_jobs PK_8586b15058c8811de6286052139; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sync_jobs
    ADD CONSTRAINT "PK_8586b15058c8811de6286052139" PRIMARY KEY (id);


--
-- Name: qa_benchmarks PK_8c91616a8e3bc0bbcabf50a1eae; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.qa_benchmarks
    ADD CONSTRAINT "PK_8c91616a8e3bc0bbcabf50a1eae" PRIMARY KEY (id);


--
-- Name: qa_execution_plans PK_8d4a060805f649ab7e5d3ff2cea; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.qa_execution_plans
    ADD CONSTRAINT "PK_8d4a060805f649ab7e5d3ff2cea" PRIMARY KEY (id);


--
-- Name: chat_meeting_peers PK_95b302f1b59b2738bbe5d15bec8; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chat_meeting_peers
    ADD CONSTRAINT "PK_95b302f1b59b2738bbe5d15bec8" PRIMARY KEY (id);


--
-- Name: chat_agent_memories PK_9fab2abee85ca798967330a296a; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chat_agent_memories
    ADD CONSTRAINT "PK_9fab2abee85ca798967330a296a" PRIMARY KEY (id);


--
-- Name: chunks PK_a306e60b8fdf6e7de1be4be1e6a; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chunks
    ADD CONSTRAINT "PK_a306e60b8fdf6e7de1be4be1e6a" PRIMARY KEY (id);


--
-- Name: documents PK_ac51aa5181ee2036f5ca482857c; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.documents
    ADD CONSTRAINT "PK_ac51aa5181ee2036f5ca482857c" PRIMARY KEY (id);


--
-- Name: chat_meeting_voice PK_b08913521aefcbc9c1a65e9f0e4; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chat_meeting_voice
    ADD CONSTRAINT "PK_b08913521aefcbc9c1a65e9f0e4" PRIMARY KEY (id);


--
-- Name: qa_organizations PK_c1417f39348b08dc7214481b32a; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.qa_organizations
    ADD CONSTRAINT "PK_c1417f39348b08dc7214481b32a" PRIMARY KEY (id);


--
-- Name: sync_work PK_c84e61d5079d32ba1d69e74e9bc; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sync_work
    ADD CONSTRAINT "PK_c84e61d5079d32ba1d69e74e9bc" PRIMARY KEY (id);


--
-- Name: qa_projects PK_caae13f960fec7057fbbcc5cab3; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.qa_projects
    ADD CONSTRAINT "PK_caae13f960fec7057fbbcc5cab3" PRIMARY KEY (id);


--
-- Name: qa_project_keys PK_d16391a4da82950508060de7668; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.qa_project_keys
    ADD CONSTRAINT "PK_d16391a4da82950508060de7668" PRIMARY KEY (id);


--
-- Name: harness_runs PK_d540aed42bc404a8c392b9a1b5d; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.harness_runs
    ADD CONSTRAINT "PK_d540aed42bc404a8c392b9a1b5d" PRIMARY KEY (id);


--
-- Name: outpost_runs PK_d79742fc4bf31641e09cd87bdde; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.outpost_runs
    ADD CONSTRAINT "PK_d79742fc4bf31641e09cd87bdde" PRIMARY KEY (id);


--
-- Name: chat_work PK_d7b5b2ebb13bc355e277b379c07; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chat_work
    ADD CONSTRAINT "PK_d7b5b2ebb13bc355e277b379c07" PRIMARY KEY (id);


--
-- Name: qa_runs PK_e0c4c807c84f464310712470a2f; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.qa_runs
    ADD CONSTRAINT "PK_e0c4c807c84f464310712470a2f" PRIMARY KEY (id);


--
-- Name: chat_meeting_activity PK_e0de01f4084e0ef470353a75945; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chat_meeting_activity
    ADD CONSTRAINT "PK_e0de01f4084e0ef470353a75945" PRIMARY KEY (id);


--
-- Name: environments PK_ec32d12469ec3c2f2f20c4f5e71; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.environments
    ADD CONSTRAINT "PK_ec32d12469ec3c2f2f20c4f5e71" PRIMARY KEY (id);


--
-- Name: chat_channels PK_efecd102855fb96e1428306ec6f; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chat_channels
    ADD CONSTRAINT "PK_efecd102855fb96e1428306ec6f" PRIMARY KEY (id);


--
-- Name: qa_healing_suggestions PK_f6a7166513d770f903274eafcc7; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.qa_healing_suggestions
    ADD CONSTRAINT "PK_f6a7166513d770f903274eafcc7" PRIMARY KEY (id);


--
-- Name: harness_executions PK_f95ac56db27942312b6e32fa4c1; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.harness_executions
    ADD CONSTRAINT "PK_f95ac56db27942312b6e32fa4c1" PRIMARY KEY (id);


--
-- Name: qa_executions PK_fdb6e8908ed2f8ce3b1a5444ac5; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.qa_executions
    ADD CONSTRAINT "PK_fdb6e8908ed2f8ce3b1a5444ac5" PRIMARY KEY (id);


--
-- Name: chat_conversations PK_ff117d9f57807c4f2e3034a39f3; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chat_conversations
    ADD CONSTRAINT "PK_ff117d9f57807c4f2e3034a39f3" PRIMARY KEY (id);


--
-- Name: qa_org_members UQ_78e243ec560432dc19ef8b1181b; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.qa_org_members
    ADD CONSTRAINT "UQ_78e243ec560432dc19ef8b1181b" UNIQUE ("keyId");


--
-- Name: chat_deliveries UQ_b1aa16ebb8d3bd4049d2608d540; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chat_deliveries
    ADD CONSTRAINT "UQ_b1aa16ebb8d3bd4049d2608d540" UNIQUE ("messageId");


--
-- Name: IDX_0105a21e2527834bb5f6d2d384; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IDX_0105a21e2527834bb5f6d2d384" ON public.qa_project_keys USING btree (digest);


--
-- Name: IDX_034231f95f5d59d15df7f9d75a; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IDX_034231f95f5d59d15df7f9d75a" ON public.chat_agents USING btree ("projectId", kind);


--
-- Name: IDX_0a6c96f2504f38e71ff728f601; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IDX_0a6c96f2504f38e71ff728f601" ON public.qa_auth_sessions USING btree ("tokenDigest");


--
-- Name: IDX_0c868e8216aea91c6048a0007f; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IDX_0c868e8216aea91c6048a0007f" ON public.outpost_activities USING btree ("projectId");


--
-- Name: IDX_0cff9c0c2473868d39dc6dbf37; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IDX_0cff9c0c2473868d39dc6dbf37" ON public.qa_project_keys USING btree ("projectId");


--
-- Name: IDX_109b85b9b498d2805b8d6827d3; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IDX_109b85b9b498d2805b8d6827d3" ON public.chat_messages USING btree ("conversationId", sequence);


--
-- Name: IDX_1901d22f15c5c419d59feb641b; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IDX_1901d22f15c5c419d59feb641b" ON public.chat_work USING btree ("messageId", "agentId");


--
-- Name: IDX_2050ff81ee18df55458988143f; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IDX_2050ff81ee18df55458988143f" ON public.qa_super_admins USING btree (email);


--
-- Name: IDX_223397fd4dd0f9f6203967f7ce; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IDX_223397fd4dd0f9f6203967f7ce" ON public.qa_audit_events USING btree ("projectId");


--
-- Name: IDX_24f72b4199f0213e06a95a1da5; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IDX_24f72b4199f0213e06a95a1da5" ON public.qa_benchmarks USING btree ("projectId", "requestId");


--
-- Name: IDX_295133be2ecd7b7f04079ed973; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IDX_295133be2ecd7b7f04079ed973" ON public.chat_meeting_signals USING btree ("meetingId", "requestId");


--
-- Name: IDX_334f330e3aa6a700ae47331dce; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IDX_334f330e3aa6a700ae47331dce" ON public.chat_installations USING btree (provider, "providerId");


--
-- Name: IDX_3affa176d37689dde8f5e080c0; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IDX_3affa176d37689dde8f5e080c0" ON public.chat_meeting_voice USING btree ("meetingId", "agentId");


--
-- Name: IDX_3c638cd7c826fdbb5ab3f7e13a; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IDX_3c638cd7c826fdbb5ab3f7e13a" ON public.chat_meeting_peers USING btree ("meetingId", "memberId");


--
-- Name: IDX_3ecc114b034dc39b0705b0ea7f; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IDX_3ecc114b034dc39b0705b0ea7f" ON public.harness_executions USING btree (status);


--
-- Name: IDX_4b47d64912f47844e8ba4c4e0e; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IDX_4b47d64912f47844e8ba4c4e0e" ON public.chat_prompts USING btree ("projectId", name);


--
-- Name: IDX_4b503567c8ae164545a7cdc59d; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IDX_4b503567c8ae164545a7cdc59d" ON public.outpost_runs USING btree ("activityId");


--
-- Name: IDX_4c73ac6887d8013d16868eb067; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IDX_4c73ac6887d8013d16868eb067" ON public.qa_org_members USING btree ("projectId");


--
-- Name: IDX_5e918293993f953c48923a780a; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IDX_5e918293993f953c48923a780a" ON public.qa_org_support_settings USING btree ("projectId");


--
-- Name: IDX_5fa34fd9d20fa8aa722e28aa6f; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IDX_5fa34fd9d20fa8aa722e28aa6f" ON public.outpost_activities USING btree ("agentId");


--
-- Name: IDX_6b7cd1ee6ead47927c1fa0359b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IDX_6b7cd1ee6ead47927c1fa0359b" ON public.documents USING btree ("contentHash");


--
-- Name: IDX_6c43526e58328baebdb0afe34c; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IDX_6c43526e58328baebdb0afe34c" ON public.qa_org_members USING btree ("projectId", email);


--
-- Name: IDX_779d43ef9889308f686c902b71; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IDX_779d43ef9889308f686c902b71" ON public.chat_work USING btree ("projectId");


--
-- Name: IDX_781b2bed5f1f4b2fe00434d9c1; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IDX_781b2bed5f1f4b2fe00434d9c1" ON public.qa_executions USING btree ("runId");


--
-- Name: IDX_7b03428098b12bc442d7d2e73d; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IDX_7b03428098b12bc442d7d2e73d" ON public.qa_org_invitations USING btree ("tokenDigest");


--
-- Name: IDX_7b952fe574fecd060a051a75cd; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IDX_7b952fe574fecd060a051a75cd" ON public.qa_org_invitations USING btree ("projectId");


--
-- Name: IDX_7c1c01d7906556b0a3ce207ecc; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IDX_7c1c01d7906556b0a3ce207ecc" ON public.outpost_runs USING btree ("projectId");


--
-- Name: IDX_7ec0130af03328801d70bdf708; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IDX_7ec0130af03328801d70bdf708" ON public.qa_executions USING btree ("agentRunId");


--
-- Name: IDX_7ed73f688185a7b10b08017885; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IDX_7ed73f688185a7b10b08017885" ON public.chat_agent_memory_revisions USING btree ("projectId", "memoryId", version);


--
-- Name: IDX_80db5a75e69262d484af81668c; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IDX_80db5a75e69262d484af81668c" ON public.qa_org_invitations USING btree (email, "projectId");


--
-- Name: IDX_8416d9403a559c08e34a8f1a6c; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IDX_8416d9403a559c08e34a8f1a6c" ON public.chat_agents USING btree ("projectId", email);


--
-- Name: IDX_84b00cce8f29d6f41960273edc; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IDX_84b00cce8f29d6f41960273edc" ON public.qa_autonomous_runs USING btree ("projectId", "requestId");


--
-- Name: IDX_87c983ba0062ceb5108e374228; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IDX_87c983ba0062ceb5108e374228" ON public.chat_meeting_runs USING btree ("meetingId", "requestId");


--
-- Name: IDX_8ca3f5e612781e19a00664594e; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IDX_8ca3f5e612781e19a00664594e" ON public.qa_oidc_attempts USING btree ("stateDigest");


--
-- Name: IDX_8e7c6026b78b21539d0bbd3ec9; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IDX_8e7c6026b78b21539d0bbd3ec9" ON public.chat_meeting_entries USING btree ("meetingId", "eventId");


--
-- Name: IDX_8f4cd8aaf482c462326282ba10; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IDX_8f4cd8aaf482c462326282ba10" ON public.harness_runs USING btree (status);


--
-- Name: IDX_903ca89fc61c4d2f7854c3debf; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IDX_903ca89fc61c4d2f7854c3debf" ON public.chat_conversations USING btree ("projectId", "dedupKey");


--
-- Name: IDX_9222a2901d5e25a3c451693d3d; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IDX_9222a2901d5e25a3c451693d3d" ON public.chat_work USING btree (status);


--
-- Name: IDX_93bb00f570757460934dfae8f9; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IDX_93bb00f570757460934dfae8f9" ON public.qa_projects USING btree ("organizationId");


--
-- Name: IDX_968fddb6fbe009db4c3eaefa21; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IDX_968fddb6fbe009db4c3eaefa21" ON public.qa_workflow_artifacts USING btree ("projectId", "requestId");


--
-- Name: IDX_984e1f9b3427aa3ebdf1e8da54; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IDX_984e1f9b3427aa3ebdf1e8da54" ON public.qa_workflow_artifacts USING btree ("projectId");


--
-- Name: IDX_988770b0383bf1d0c4bf6edc01; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IDX_988770b0383bf1d0c4bf6edc01" ON public.qa_autonomous_suites USING btree ("projectId");


--
-- Name: IDX_9e0835c32e71574a0f65c77cbb; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IDX_9e0835c32e71574a0f65c77cbb" ON public.outpost_runs USING btree (status);


--
-- Name: IDX_a350965d972e4ea5e99e43b1f9; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IDX_a350965d972e4ea5e99e43b1f9" ON public.chat_tasks USING btree ("messageId");


--
-- Name: IDX_a44286210404b357521872e822; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IDX_a44286210404b357521872e822" ON public.chat_agent_memories USING btree ("projectId", "agentId", status, importance);


--
-- Name: IDX_ac780421e63bf8a15e62995214; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IDX_ac780421e63bf8a15e62995214" ON public.qa_benchmarks USING btree ("projectId");


--
-- Name: IDX_b2fae9ada8389c9c4ffc06c0e8; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IDX_b2fae9ada8389c9c4ffc06c0e8" ON public.qa_executions USING btree ("testId");


--
-- Name: IDX_b5a13a1204c67f1b4e059857d6; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IDX_b5a13a1204c67f1b4e059857d6" ON public.chat_conversations USING btree ("projectId");


--
-- Name: IDX_baba393a7d47f843cc04928fa4; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IDX_baba393a7d47f843cc04928fa4" ON public.outpost_runs USING btree ("activityId", "requestId");


--
-- Name: IDX_bc77194d5e9d2a93dd60bd1f1a; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IDX_bc77194d5e9d2a93dd60bd1f1a" ON public.chat_messages USING btree ("conversationId", "requestId");


--
-- Name: IDX_bce5472080c96437f97c218f36; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IDX_bce5472080c96437f97c218f36" ON public.qa_runs USING btree ("requestId");


--
-- Name: IDX_bd3e70ae6aad0f60aa228fb49a; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IDX_bd3e70ae6aad0f60aa228fb49a" ON public.chat_installations USING btree ("projectId");


--
-- Name: IDX_c468d5a40f3442ba8602d0b6ae; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IDX_c468d5a40f3442ba8602d0b6ae" ON public.harness_runs USING btree ("requestId");


--
-- Name: IDX_cc0d06bd6ddd8d56c2c8e13b1c; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IDX_cc0d06bd6ddd8d56c2c8e13b1c" ON public.chat_prompts USING btree ("projectId");


--
-- Name: IDX_cfcf94389d2c1a71d04fac57f8; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IDX_cfcf94389d2c1a71d04fac57f8" ON public.chunks USING btree ("chunkIndex");


--
-- Name: IDX_d2f5c180840199e528fc7f1934; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IDX_d2f5c180840199e528fc7f1934" ON public.outpost_activities USING btree ("projectId", "agentId", key);


--
-- Name: IDX_dde80333afea15eda45685365c; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IDX_dde80333afea15eda45685365c" ON public.chat_meetings USING btree ("projectId", "requestId");


--
-- Name: IDX_e300d63d6930a41c522f1c92cc; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IDX_e300d63d6930a41c522f1c92cc" ON public.chat_meeting_activity USING btree ("meetingId", sequence);


--
-- Name: IDX_e547f95b854b97fe6da02c7efd; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IDX_e547f95b854b97fe6da02c7efd" ON public.harness_executions USING btree ("requestId");


--
-- Name: IDX_e5a2e6c1b0d2fcc618a873b372; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IDX_e5a2e6c1b0d2fcc618a873b372" ON public.documents USING btree ("externalId");


--
-- Name: IDX_f45561554b3a5f09f82fb6edc3; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IDX_f45561554b3a5f09f82fb6edc3" ON public.chat_agents USING btree ("projectId");


--
-- Name: IDX_f519b55d4db4bacd3faad5213b; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IDX_f519b55d4db4bacd3faad5213b" ON public.chat_agent_prompt_installs USING btree ("projectId", "agentId", scenario);


--
-- Name: IDX_fb2104f66ce14bfdecae97c6fb; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IDX_fb2104f66ce14bfdecae97c6fb" ON public.qa_auth_sessions USING btree ("memberId");


--
-- Name: IDX_fbcdcb86cbe0c72f34450e074f; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IDX_fbcdcb86cbe0c72f34450e074f" ON public.chat_channels USING btree ("installationId", "externalId");


--
-- Name: chat_agent_memories_active_content; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX chat_agent_memories_active_content ON public.chat_agent_memories USING btree ("projectId", "agentId", "contentHash") WHERE ((status)::text = 'active'::text);


--
-- Name: chat_meeting_activity_request_unique; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX chat_meeting_activity_request_unique ON public.chat_meeting_activity USING btree ("meetingId", "requestId") WHERE ("requestId" IS NOT NULL);


--
-- Name: sync_work_job_external_id; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX sync_work_job_external_id ON public.sync_work USING btree (sync_job_id, "externalId");


--
-- Name: sync_jobs FK_24cf8819d7ceeeea29143fd3fb3; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sync_jobs
    ADD CONSTRAINT "FK_24cf8819d7ceeeea29143fd3fb3" FOREIGN KEY (source_id) REFERENCES public.sources(id) ON DELETE CASCADE;


--
-- Name: documents FK_5e12dcaf3b5d5fdffc8f1e32177; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.documents
    ADD CONSTRAINT "FK_5e12dcaf3b5d5fdffc8f1e32177" FOREIGN KEY (source_id) REFERENCES public.sources(id) ON DELETE CASCADE;


--
-- Name: business_items FK_7541bd94715c25fb9aa1d61bb46; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.business_items
    ADD CONSTRAINT "FK_7541bd94715c25fb9aa1d61bb46" FOREIGN KEY ("sourceId") REFERENCES public.sources(id) ON DELETE SET NULL;


--
-- Name: qa_executions FK_781b2bed5f1f4b2fe00434d9c1f; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.qa_executions
    ADD CONSTRAINT "FK_781b2bed5f1f4b2fe00434d9c1f" FOREIGN KEY ("runId") REFERENCES public.qa_runs(id) ON DELETE CASCADE;


--
-- Name: agent_tasks FK_8fd1ceb7df845fef211603e549b; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.agent_tasks
    ADD CONSTRAINT "FK_8fd1ceb7df845fef211603e549b" FOREIGN KEY ("sessionId") REFERENCES public.agent_sessions(id) ON DELETE SET NULL;


--
-- Name: business_relationships FK_9e59013159f041746be9f32b996; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.business_relationships
    ADD CONSTRAINT "FK_9e59013159f041746be9f32b996" FOREIGN KEY ("toItemId") REFERENCES public.business_items(id) ON DELETE CASCADE;


--
-- Name: business_relationships FK_b2de484a3927b1dd0b4bfd12880; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.business_relationships
    ADD CONSTRAINT "FK_b2de484a3927b1dd0b4bfd12880" FOREIGN KEY ("fromItemId") REFERENCES public.business_items(id) ON DELETE CASCADE;


--
-- Name: chunks FK_d841de45a719fe1f35213d79207; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chunks
    ADD CONSTRAINT "FK_d841de45a719fe1f35213d79207" FOREIGN KEY (document_id) REFERENCES public.documents(id) ON DELETE CASCADE;


--
-- Name: sync_work FK_da7a76366d4c9c8e6e59e09e3e8; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sync_work
    ADD CONSTRAINT "FK_da7a76366d4c9c8e6e59e09e3e8" FOREIGN KEY (sync_job_id) REFERENCES public.sync_jobs(id) ON DELETE CASCADE;


--
-- Name: business_items FK_e5e9fce03fc36b1c9ce82adeea7; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.business_items
    ADD CONSTRAINT "FK_e5e9fce03fc36b1c9ce82adeea7" FOREIGN KEY ("documentId") REFERENCES public.documents(id) ON DELETE SET NULL;


--
-- PostgreSQL database dump complete
--


COMMIT;
