import os
from playwright.sync_api import sync_playwright, expect


def run():
    base = os.environ['CHAT_WEB_URL']
    with sync_playwright() as playwright:
        browser = playwright.chromium.launch(args=['--use-fake-device-for-media-stream', '--use-fake-ui-for-media-stream'])
        owner = browser.new_context(viewport={'width': 1440, 'height': 960})
        teammate = browser.new_context(viewport={'width': 1280, 'height': 900})
        for context, variable in [(owner, 'CHAT_OWNER_COOKIE'), (teammate, 'CHAT_MEMBER_COOKIE')]:
            context.grant_permissions(['camera', 'microphone'])
            context.add_init_script('window.meetingSpeech = []; const originalSpeak = speechSynthesis.speak.bind(speechSynthesis); speechSynthesis.speak = utterance => { window.meetingSpeech.push(utterance.text); originalSpeak(utterance); };')
            context.add_cookies([{'name': 'qa_session', 'value': os.environ[variable].split('=', 1)[1], 'url': base}])
        page = owner.new_page()
        failures = []
        page.on('pageerror', lambda failure: failures.append(str(failure)))
        page.goto(base + '/chat')
        page.get_by_role('button', name='Manage agents', exact=False).click()
        expect(page.get_by_role('dialog')).to_contain_text('QAE')
        expect(page.get_by_role('dialog')).to_contain_text('AUE')
        expect(page.get_by_role('button', name='New agent', exact=True)).to_have_count(0)
        page.get_by_role('button', name='AUE AUE', exact=True).click()
        page.get_by_label('Agent name', exact=True).fill('Jordan')
        page.get_by_role('button', name='Save name', exact=True).click()
        expect(page.get_by_role('dialog')).to_have_count(0)
        page.get_by_role('button', name='New conversation', exact=True).click()
        page.get_by_role('button', name='Group', exact=True).click()
        page.get_by_label('Group name', exact=True).fill('Release discussion')
        page.get_by_label('person@chat.test', exact=True).check()
        page.get_by_label('Agent (optional)', exact=True).select_option(os.environ['CHAT_AGENT_ID'])
        page.get_by_label('What should the agent do in this chat?').fill('Help plan release testing and suggest tasks.')
        page.get_by_role('button', name='Start conversation', exact=True).click()
        expect(page.get_by_role('heading', name='Release discussion', exact=True)).to_be_visible()
        page.get_by_role('textbox', name='Message', exact=True).fill('@Alex help us plan testing')
        page.get_by_role('button', name='Send message', exact=True).click()
        expect(page.get_by_text('Here is a test plan.', exact=True)).to_be_visible(timeout=20000)
        expect(page.get_by_text('Check login and logout.', exact=True)).to_be_visible()
        page.get_by_role('button', name='Create task', exact=True).last.click()
        expect(page.get_by_text('Task created', exact=True)).to_be_visible()
        page.get_by_role('button', name='Conversation tasks', exact=True).click()
        expect(page.get_by_role('dialog')).to_contain_text('Review login coverage')
        page.get_by_role('button', name='Mark complete').click()
        expect(page.get_by_role('dialog')).to_contain_text('Completed')
        page.get_by_role('button', name='Close dialog').click()
        other = teammate.new_page()
        other.goto(base + '/chat')
        other.get_by_role('button', name='Release discussion', exact=False).click()
        expect(other.get_by_text('Here is a test plan.', exact=True)).to_be_visible()
        other.get_by_role('textbox', name='Message', exact=True).fill('I will review the login cases.')
        other.get_by_role('button', name='Send message', exact=True).click()
        expect(page.get_by_text('I will review the login cases.', exact=True)).to_be_visible(timeout=10000)
        page.get_by_role('button', name='Calls & meetings', exact=True).click()
        page.get_by_label('Participation', exact=True).select_option('active')
        page.get_by_label('I am authorized to start this meeting', exact=False).check()
        page.get_by_role('button', name='Start native call', exact=True).click()
        page.get_by_label('I agree to AI-assisted notes', exact=False).check()
        page.get_by_role('button', name='Join call', exact=True).click()
        expect(page.get_by_role('button', name='Leave call', exact=True)).to_be_visible(timeout=15000)
        other.get_by_role('button', name='Calls & meetings', exact=True).click()
        other.get_by_role('button', name='Native call · Active participant', exact=False).click()
        other.get_by_label('I agree to AI-assisted notes', exact=False).check()
        other.get_by_role('button', name='Join call', exact=True).click()
        expect(page.get_by_text('person@chat.test · connected', exact=True)).to_be_visible(timeout=20000)
        expect(other.get_by_text('owner@chat.test · connected', exact=True)).to_be_visible(timeout=20000)
        page.wait_for_function('Array.from(document.querySelectorAll("video")).filter(video => !video.muted).some(video => video.videoWidth > 0 && video.readyState >= 2)')
        page.get_by_role('button', name='Mute microphone', exact=True).click()
        expect(page.get_by_role('button', name='Unmute microphone', exact=True)).to_be_visible()
        page.get_by_role('button', name='Unmute microphone', exact=True).click()
        page.get_by_role('textbox', name='Manual transcript entry', exact=True).fill('We need to review login tests before release.')
        page.get_by_role('button', name='Add', exact=True).click()
        expect(other.get_by_label('Meeting transcript')).to_contain_text('We need to review login tests before release.', timeout=10000)
        page.get_by_role('button', name='Compile notes', exact=True).click()
        expect(page.get_by_text('The team discussed login coverage.', exact=True)).to_be_visible(timeout=15000)
        expect(page.get_by_role('link', name='Source 1', exact=True)).to_be_visible()
        page.get_by_role('button', name='Approve & publish notes', exact=True).click()
        expect(page.get_by_role('button', name='Published to conversation', exact=True)).to_be_disabled()
        page.get_by_role('button', name='Ask agent to participate', exact=True).click()
        expect(page.get_by_text('Which login flows are release-critical?', exact=True)).to_be_visible(timeout=15000)
        page.get_by_role('button', name='Speak to native call', exact=True).click()
        page.wait_for_function('window.meetingSpeech.includes("Which login flows are release-critical?")')
        other.wait_for_function('window.meetingSpeech.includes("Which login flows are release-critical?")')
        page.screenshot(path='/tmp/superqa-meeting-desktop.png')
        page.set_viewport_size({'width': 390, 'height': 844})
        assert page.evaluate('document.documentElement.scrollWidth <= window.innerWidth'), 'Meeting page overflowed'
        page.screenshot(path='/tmp/superqa-meeting-mobile.png')
        page.set_viewport_size({'width': 1440, 'height': 960})
        page.get_by_role('button', name='End meeting / stop agent', exact=True).click()
        expect(other.get_by_role('button', name='Join call', exact=True)).to_be_disabled(timeout=10000)
        page.get_by_role('button', name='Close dialog', exact=True).click()
        other.get_by_role('button', name='Close dialog', exact=True).click()
        expect(page.get_by_text('Reviewed meeting notes: The team discussed login coverage.', exact=True)).to_be_visible(timeout=10000)
        page.screenshot(path=os.environ.get('CHAT_SCREENSHOT', '/tmp/superqa-chat-desktop.png'))
        page.set_viewport_size({'width': 390, 'height': 844})
        expect(page.get_by_role('textbox', name='Message', exact=True)).to_be_visible()
        assert page.evaluate('document.documentElement.scrollWidth <= window.innerWidth'), 'Mobile page overflowed'
        page.screenshot(path='/tmp/superqa-chat-mobile.png')
        page.get_by_role('button', name='Back to conversations').click()
        page.get_by_role('button', name='New conversation', exact=True).click()
        page.get_by_label('person@chat.test', exact=True).check()
        page.get_by_role('button', name='Start conversation', exact=True).click()
        page.get_by_role('textbox', name='Message', exact=True).fill('A private message for you.')
        page.get_by_role('button', name='Send message', exact=True).click()
        expect(page.get_by_text('A private message for you.', exact=True)).to_be_visible()
        page.reload()
        page.get_by_role('button', name='person@chat.test', exact=False).click()
        expect(page.get_by_text('A private message for you.', exact=True)).to_be_visible()
        page.goto(base + '/calendar')
        expect(page.get_by_role('heading', name='Calendar', exact=True)).to_be_visible()
        expect(page.get_by_text('qae@calendar.test', exact=True)).to_be_visible()
        expect(page.get_by_role('button', name='Upcoming release readiness', exact=False)).to_be_visible()
        page.get_by_role('button', name='Upcoming release readiness', exact=False).click()
        expect(page.get_by_role('dialog')).to_contain_text('organizer@calendar.test')
        expect(page.get_by_role('dialog')).to_contain_text('Teammate')
        page.get_by_role('button', name='Skip / stop this meeting', exact=True).click()
        expect(page.get_by_role('button', name='Allow scheduled join', exact=True)).to_be_visible()
        page.get_by_role('button', name='Close dialog', exact=True).click()
        page.set_viewport_size({'width': 1440, 'height': 960})
        page.screenshot(path='/tmp/superqa-calendar-desktop.png')
        page.set_viewport_size({'width': 390, 'height': 844})
        assert page.evaluate('document.documentElement.scrollWidth <= window.innerWidth'), 'Calendar page overflowed'
        page.screenshot(path='/tmp/superqa-calendar-mobile.png')
        page.goto(base + '/meetings')
        page.get_by_role('button', name='Sprint QA planning', exact=False).click()
        expect(page.get_by_role('dialog')).to_contain_text('Sprint QA planning')
        expect(page.get_by_text('The team discussed login coverage.', exact=True)).to_be_visible(timeout=10000)
        page.get_by_text('2 invitees & RSVP details', exact=True).click()
        expect(page.get_by_role('dialog')).to_contain_text('person@chat.test')
        page.get_by_role('button', name='Close dialog', exact=True).click()
        page.set_viewport_size({'width': 1440, 'height': 960})
        if not page.get_by_role('button', name='QAE', exact=True).is_visible():
            page.get_by_role('button', name='Agents', exact=True).click()
        page.get_by_role('button', name='QAE', exact=True).click()
        page.locator('main').get_by_role('button', name='Calendar', exact=True).click()
        expect(page.get_by_role('heading', name='Calendar', exact=True)).to_be_visible()
        expect(page.get_by_text('qae@calendar.test', exact=True)).to_be_visible()
        page.get_by_role('button', name='AUE', exact=True).click()
        page.locator('main').get_by_role('button', name='Meetings', exact=True).click()
        expect(page.get_by_text('No meeting history yet.', exact=True)).to_be_visible()
        assert failures == [], failures
        browser.close()


if __name__ == '__main__':
    run()
