'use client';
import type { InspectorSelection, PageKey, WorkspaceSeed } from '../lib/types';
type Props = { data: WorkspaceSeed; setPage:(page:PageKey)=>void; setSelected:(selection:InspectorSelection)=>void };
const kpis = [['Passed','1,284','+8.2%','good'],['Failed','37','-12.4%','bad'],['Blocked','9','+2','warn'],['Running','14','live','info'],['Skipped','42','-5','muted'],['Duration','46m','-11m','good'],['AI Confidence','91%','+3%','ai'],['Healing Count','22','5 pending','ai']];
export function DashboardScreen({ setPage }: Props){ return <div className="stack"><KpiGrid/><div className="grid two"><Chart title="Execution Trends"/><Heatmap title="Failure Heatmap"/></div><div className="grid three"><Card title="Recent Executions"><Mini items={['Execution #14 failed 37 tests','Preview run currently executing','Nightly smoke passed 99%']} onClick={() => setPage('executions')}/></Card><Card title="Agent Activity"><Mini items={['Healer proposed 5 fixes','Context Manager verified 28 facts','Executor streamed 1.2k events']}/></Card><Card title="AI Insights"><Mini items={['Checkout Payment coverage below target','SSO flow is stable across browsers','Zephyr token expires soon']}/></Card></div><div className="grid two"><Card title="Pending Clarifications"><Clarification/></Card><Card title="Knowledge Graph Preview"><Graph/></Card></div></div>; }
export function ExecutionsScreen({ data, setSelected }: Props){ return <div className="stack"><KpiGrid/><Toolbar filters={['Search','Environment','Browser','Tags','Status','Date']}/><DataTable headers={['Test Name','Flow','Browser','Environment','Status','Duration','Retry','AI Confidence','Owner']} rows={data.executions.map(e=>[e.testName,e.flow,e.browser,e.environment,e.status,e.duration,e.retry,`${e.confidence}%`,e.owner])} onRow={row => setSelected({ type:'Test Case', title:String(row[0]), status:String(row[4]), confidence:String(row[7]) })}/></div>; }
export function RunScreen({ setSelected }: Props){ const steps=['Load checkout','Create user data','Enter card','Click Pay now','Assert decline banner']; return <div className="grid run-grid"><Card title="Timeline"><ol className="timeline">{steps.map((step,index)=><li key={step} onClick={() => setSelected({ type:'Step', title:step, status:index === 3 ? 'Failed' : 'Passed', confidence:index === 3 ? '87%' : '98%' })}><span className={`dot ${index === 3 ? 'bad' : 'good'}`}/><b>{step}</b><small>{index * 11 + 4}s</small></li>)}</ol></Card><Card title="Evidence Viewer"><Screenshot/></Card><Card title="AI Reasoning Trace"><pre>{`[agent] observing DOM snapshot\n[executor] click Pay now\n[network] POST /payments -> 402\n[ai] likely product behavior changed: error banner text differs\n[healer] suggested resilient role locator`}</pre></Card></div>; }
export function HealerScreen({ data, setSelected }: Props){ return <div className="grid two"><div className="stack"><Toolbar filters={['Confidence','Risk','Owner','Created','Affected tests']}/><DataTable headers={['Issue','Affected Tests','Locator','Suggested Locator','Confidence','Risk','Owner']} rows={data.healing.map(h=>[h.issue,h.affectedTests,h.locator,h.suggestedLocator,`${h.confidence}%`,h.risk,h.owner])} onRow={row => setSelected({ type:'Healing Suggestion', title:String(row[0]), status:String(row[5]), confidence:String(row[4]) })}/></div><Card title="Diff Viewer · Locator Comparison"><div className="diff"><p className="remove">- button[data-testid=&quot;pay-now&quot;]</p><p className="add">+ getByRole('button', {'{ name: "Pay now" }'})</p><p>Confidence 94% · blast radius 12 tests · risk low</p><button className="btn primary">Approve</button><button className="btn">Reject</button></div></Card></div>; }
export function ContextScreen({ data, setSelected }: Props){ return <div className="stack"><div className="cards integrations">{data.integrations.map(integration => <button className="integration" key={integration.name} onClick={() => setSelected({ type:'Integration', title:integration.name, status:integration.status, confidence:'Synced' })}><span className="big">◎</span><strong>{integration.name}</strong><span className={`pill ${integration.status === 'Warning' ? 'warn' : 'good'}`}>{integration.status}</span><small>Last sync {integration.lastSync}</small><small>{integration.permissions}</small></button>)}</div><div className="grid two"><Card title="Clarification UI"><Clarification/></Card><Card title="Knowledge Graph"><Graph/></Card></div></div>; }
export function FlowsScreen(){ return <div className="grid two"><Card title="Business Hierarchy"><div className="tree-static">Flows<br/>└ Module<br/>&nbsp;&nbsp;├ Authentication<br/>&nbsp;&nbsp;│ ├ Login<br/>&nbsp;&nbsp;│ ├ Registration<br/>&nbsp;&nbsp;│ └ Forgot Password<br/>&nbsp;&nbsp;└ Checkout<br/>&nbsp;&nbsp;&nbsp;&nbsp;├ Add Item<br/>&nbsp;&nbsp;&nbsp;&nbsp;├ Payment<br/>&nbsp;&nbsp;&nbsp;&nbsp;└ Confirmation</div></Card><Card title="Login Flow"><div className="stats"><span>Risk <b>High</b></span><span>Priority <b>P0</b></span><span>Coverage <b>88%</b></span><span>Automation <b>76%</b></span></div><Heatmap title="Coverage Heatmap"/></Card></div>; }
export function FactsScreen(){ return <div className="stack"><Toolbar filters={['Category','Confidence','Source','Verified','Related object']}/><DataTable headers={['Fact','Category','Confidence','Source','Created By','Updated By','Related Objects','AI Generated','Human Verified']} rows={[['A locked account cannot start checkout','Business Rule','96%','Confluence','Context Agent','Maya','Checkout, User','Yes','Yes'],['Payment decline must show retry CTA','Validation Rule','91%','Jira','Context Agent','Ravi','Payment','Yes','No']]}/></div>; }
export function ActionsScreen(){ return <div className="grid code-grid"><Card title="Action Tree"><Mini items={['Login Page / clickLogin()','Login Page / enterEmail()','Checkout / clickPayNow()','Checkout / verifyToast()']}/></Card><Card title="Monaco-style Source Code"><pre>{`async function clickPayNow(page) {\n  await page.getByRole('button', { name: 'Pay now' }).click();\n  await expect(page.getByText('Processing')).toBeVisible();\n}`}</pre></Card><Card title="AI Explanation"><p>Uses an accessible role locator for better stability and healing confidence. Usage count: 12 tests.</p></Card></div>; }
export function DomScreen(){ return <div className="grid dom-grid"><Card title="Screenshot"><Screenshot/></Card><Card title="DOM Tree and Locator Tree"><pre>{`main#checkout\n  form.payment\n    input[name=cardNumber]\n    button[role=button] "Pay now"`}</pre></Card><Card title="Accessibility"><Mini items={['Button has accessible name','Input missing description','Color contrast passes AA']}/></Card></div>; }
export function DataSetupScreen(){ return <div className="grid two"><Card title="Entity Data Builders"><Mini items={['User / Create','User / Update','User / Delete','User / Archive','User / Deactivate']}/></Card><Card title="Preview and Execution History"><DataTable headers={['Mode','Status','Last Execution']} rows={[['UI','Supported','Passed 2h ago'],['API','Supported','Passed 12m ago'],['Database','Supported','Passed 1d ago'],['Fixture','Supported','Never']]}/></Card></div>; }
export function TestCasesScreen({ data, setSelected }: Props){ return <div className="stack"><Toolbar filters={['ID or title','Priority','Automation','Owner','Flow','Risk','AI Score']}/><DataTable headers={['ID','Title','Priority','Automation','Owner','Flow','Tags','Last Run','Pass Rate','Coverage','Risk','AI Score']} rows={data.testCases.map(test=>[test.id,test.title,test.priority,test.automation,test.owner,test.flow,test.tags.join(', '),test.lastRun,`${test.passRate}%`,`${test.coverage}%`,test.risk,test.aiScore])} onRow={row => setSelected({ type:'Test Case', title:`${row[0]} ${row[1]}`, status:String(row[7]), confidence:`${row[11]}%` })}/><Card title="Professional Editable Test Steps"><DataTable headers={['Step','Action','Expected','Data','Locator','Automation Method','Status','Comments']} rows={[[1,'enterEmail()','Email appears','validUser.email','#email','Playwright','Automated','Stable'],[2,'enterPassword()','Password accepted','secret','#password','Playwright','Automated','Masked'],[3,'clickLogin()','Dashboard opens','n/a','role button','Playwright','Automated','Healed once']]}/></Card></div>; }
export function CoverageScreen(){ return <div className="stack"><div className="grid three"><Chart title="Business Coverage"/><Chart title="Requirement Coverage"/><Chart title="Automation %"/></div><DataTable headers={['Area','Requirement','Current Coverage','Risk','Missing Tests','Recommended Action','AI Confidence']} rows={[['Checkout Payment','Decline handling','42%','High','8','Generate tests','93%'],['Authentication','SSO login','94%','High','1','Link fact','88%']]}/></div>; }
export function PullRequestsScreen(){ return <div className="stack"><Toolbar filters={['Open','Awaiting Review','Approved','Rejected','Merged']}/><DataTable headers={['PR','Type','Author Agent','Reviewer','Status','Tests Changed','Risk','Created']} rows={[['PR-128','Healing','Healer','Maya Chen','Awaiting Review','12','Low','8m ago'],['PR-129','Coverage','Test Case Manager','Ravi Patel','Checks running','8','Medium','16m ago']]}/><Card title="Before / After / Diff"><div className="diff"><p className="remove">- legacy selector</p><p className="add">+ accessible role selector</p></div></Card></div>; }
export function SettingsScreen(props: Props){ return <ContextScreen {...props}/>; }
function KpiGrid(){ return <div className="kpis">{kpis.map(kpi=><div className="kpi" key={kpi[0]}><span>{kpi[0]}</span><strong>{kpi[1]}</strong><em className={kpi[3]}>{kpi[2]}</em></div>)}</div>; }
function Toolbar({ filters }: { filters:string[] }){ return <div className="toolbar">{filters.map(filter=><button className="filter" key={filter}>{filter}⌄</button>)}<button className="btn">Export</button><button className="btn">Saved view</button></div>; }
function DataTable({ headers, rows, onRow }: { headers:string[]; rows:(string|number)[][]; onRow?:(row:(string|number)[])=>void }){ return <div className="tablewrap"><table><thead><tr>{headers.map(header=><th key={header}>{header}</th>)}</tr></thead><tbody>{rows.map((row,index)=><tr key={index} onClick={() => onRow?.(row)}>{row.map((cell,index)=><td key={index}><Cell value={cell}/></td>)}</tr>)}</tbody></table></div>; }
function Cell({ value }: { value:string|number }){ const text=String(value); const cls=text==='Failed'?'bad':text==='Passed'||text==='Connected'||text==='Automated'?'good':text==='Blocked'||text==='Warning'?'warn':text==='Running'?'info':''; return cls ? <span className={`pill ${cls}`}>{text}</span> : <>{text}</>; }
function Card({ title, children }: { title:string; children:React.ReactNode }){ return <section className="card"><h3>{title}</h3>{children}</section>; }
function Chart({ title }: { title:string }){ return <Card title={title}><div className="chart">{[35,54,42,70,58,86,74,92].map((height,index)=><span style={{ height:`${height}%` }} key={index}/>)}</div></Card>; }
function Heatmap({ title }: { title:string }){ return <Card title={title}><div className="heat">{Array.from({ length:35 },(_,index)=><span className={['a','b','c','d'][index % 4]} key={index}/>)}</div></Card>; }
function Mini({ items, onClick }: { items:string[]; onClick?:()=>void }){ return <ul className="mini">{items.map(item=><li onClick={onClick} key={item}>✓ {item}</li>)}</ul>; }
function Clarification(){ return <div className="chat"><p>🤖 I found multiple login flows. Which one should become the canonical flow?</p><div><button className="btn primary">Accept</button><button className="btn">Reject</button><button className="btn">Merge</button><button className="btn">Answer</button></div></div>; }
function Graph(){ return <div className="graph">{['Pages','Flows','Facts','Actions','Requirements'].map((node,index)=><span style={{ left:`${20 + index * 18}%`, top:`${20 + (index % 2) * 45}%` }} key={node}>{node}</span>)}</div>; }
function Screenshot(){ return <div className="screenshot"><div className="browserbar"/><div className="fakepage"><input placeholder="Card number"/><button>Pay now</button><span className="target"/></div></div>; }
