#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="$SCRIPT_DIR/../apps/api/.env"

TOTAL_STAGES=6

banner "Teams meeting auto-join setup"

say "Already done for you: DB migrations for meetings/calendar are applied,"
say "and CHAT_SECRET_KEY / CHAT_WORKER_ENABLED are already set in apps/api/.env."
say "This wizard covers the rest: the parts that need your Azure, Recall and"
say "Microsoft Teams accounts, which only you can click through."
pause

# ── Stage 1: public reachability for OAuth + webhooks ─────────────────────
stage "Public reachability (Microsoft OAuth + Recall webhooks)"
say "Microsoft's OAuth redirect allows plain http://localhost in dev, but"
say "Recall's webhook callback must reach a real public HTTPS endpoint of"
say "your API, since Recall's servers deliver events to it over the internet."
say ""
say "Two options:"
step "Pilot/dev: in another terminal run 'ngrok http 4000' (forwards your"
say "    local API on port 4000) and copy the https forwarding URL it prints."
step "Already deployed: use your real HTTPS domain for the API, no /api suffix."
say ""
note "Your web app origin (for the OAuth redirect) can stay http://localhost:3000"
note "for this pilot - only the API origin below needs to be publicly reachable."
ask AUTH_PUBLIC_URL "Public WEB origin (Enter to keep current):"
ask MEETING_PUBLIC_API_URL "Public API origin for Recall webhooks (e.g. the ngrok https URL, no /api suffix):"
MEETING_PUBLIC_API_URL="${MEETING_PUBLIC_API_URL%/}"
MEETING_PUBLIC_API_URL="${MEETING_PUBLIC_API_URL%/api}"
write_env AUTH_PUBLIC_URL "$AUTH_PUBLIC_URL"
write_env MEETING_PUBLIC_API_URL "$MEETING_PUBLIC_API_URL"
note "Keep that tunnel (or your deployment) running whenever you want live bots to work."

# ── Stage 2: Microsoft Entra app registration ──────────────────────────────
stage "Microsoft Entra app (calendar OAuth)"
say "This lets the app read the dedicated mailbox's calendar invitations."
open_url "https://portal.azure.com/#view/Microsoft_AAD_RegisteredApps/ApplicationsListBlade"
step "Microsoft Entra ID -> App registrations -> New registration."
step "Name: anything, e.g. 'Super QA Calendar'."
step "Supported account types: 'Accounts in this organizational directory only (Single tenant)'."
step "Platform: Web. Redirect URI, paste exactly:"
say "    ${BOLD}${AUTH_PUBLIC_URL}/calendar/callback${RESET}"
step "After creation, copy the 'Application (client) ID' from the Overview page."
ask MICROSOFT_CALENDAR_CLIENT_ID "Application (client) ID:"
step "Certificates & secrets -> New client secret -> copy the secret VALUE now"
say "    (Azure only shows it once)."
ask_secret MICROSOFT_CALENDAR_CLIENT_SECRET "Client secret value:"
step "API permissions -> Add a permission -> Microsoft Graph -> Delegated ->"
say "    add Calendars.Read, User.Read, offline_access. Grant admin consent"
say "    if your tenant requires it."
write_env MICROSOFT_CALENDAR_CLIENT_ID "$MICROSOFT_CALENDAR_CLIENT_ID"
write_env MICROSOFT_CALENDAR_CLIENT_SECRET "$MICROSOFT_CALENDAR_CLIENT_SECRET"

# ── Stage 3: Recall.ai meeting-bot provider ────────────────────────────────
stage "Recall.ai meeting-bot provider"
say "This is the service that actually dispatches a bot into the Teams call -"
say "separate from the Entra app above, which only grants calendar read access."
open_url "https://recall.ai"
step "Sign up or log in, then open your dashboard."
step "Copy your API key."
ask_secret RECALL_API_KEY "Recall API key:"
step "Confirm your account's region in the dashboard (don't guess - it must"
say "    match exactly). Common values look like 'us-west-2'."
ask RECALL_REGION "Recall region:"
step "Under webhook/callback settings, copy the workspace webhook verification"
say "    secret (shown as whsec_...)."
ask_secret RECALL_WEBHOOK_SECRET "Recall webhook secret (whsec_...):"
write_env RECALL_API_KEY "$RECALL_API_KEY"
write_env RECALL_REGION "$RECALL_REGION"
write_env RECALL_WEBHOOK_SECRET "$RECALL_WEBHOOK_SECRET"
note "Recall webhook endpoint to configure if asked: ${MEETING_PUBLIC_API_URL}/api/meeting-hooks/recall"

# ── Stage 4: restart the API ───────────────────────────────────────────────
stage "Restart the API"
say "The new environment variables only take effect after a restart."
step "From the repo root: npm run start:dev -w apps/api"
say "    (or restart however you normally run the API process)."
if confirm "Keep your tunnel from Stage 1 running too, if you used one. Done restarting?"; then
  note "Good - continuing."
else
  warn "Restart it before continuing, or the next stage's OAuth consent will fail."
fi

# ── Stage 5: connect the mailbox in the app UI ─────────────────────────────
stage "Connect the mailbox (in-app, interactive OAuth)"
say "This step needs your own browser login as the exact dedicated mailbox -"
say "it can't be scripted."
open_url "$AUTH_PUBLIC_URL"
step "Go to Calendar -> Connect mailbox."
step "Choose QAE or AUE."
step "Provider: Microsoft."
step "Enter the dedicated organization-owned mailbox email (a real work/school"
say "    mailbox you control - not a personal Microsoft account)."
step "Choose default participation mode (silent note-taker vs active participant)"
say "    and a sharing conversation."
step "Complete the Microsoft consent screen signed in as exactly that mailbox"
say "    address - a different signed-in account is rejected."
confirm "Connected and consent completed successfully?" || warn "Resolve that before sending a test invite."

# ── Stage 6: live verification ──────────────────────────────────────────────
stage "Live verification"
step "Send a real Microsoft Teams meeting invite to the connected mailbox."
step "Check the app's Calendar view - the event should appear before start time."
step "At meeting start: the host must manually admit the bot from the Teams"
say "    lobby (5-minute lobby limit, 1-hour max meeting length in this pilot)."
step "Confirm the bot joins, posts its AI disclosure, and that a transcript/"
say "    notes run shows up afterward in the Meetings view."
confirm "Bot joined and transcript/notes appeared?" || note "See docs/calendar-auto-join.md for troubleshooting (sync lease timing, missed/declined events, etc.)."

finish
