export const mockTestCases = [
  {
    id: 'TC-1001',
    title: 'Login with valid enterprise SSO user',
    priority: 'P0',
    automation: 'automated',
    owner: 'Maya Chen',
    flow: 'Authentication / Login',
    tags: ['sso', 'auth', 'critical'],
    lastRun: new Date('2024-01-15T10:30:00Z'),
    passRate: 98,
    coverage: 85,
    risk: 'high',
    aiScore: 94,
  },
  {
    id: 'TC-1002',
    title: 'Login with invalid credentials shows error',
    priority: 'P0',
    automation: 'automated',
    owner: 'Maya Chen',
    flow: 'Authentication / Login',
    tags: ['auth', 'negative'],
    lastRun: new Date('2024-01-15T10:32:00Z'),
    passRate: 100,
    coverage: 90,
    risk: 'high',
    aiScore: 96,
  },
  {
    id: 'TC-1042',
    title: 'Payment decline shows error banner',
    priority: 'P0',
    automation: 'automated',
    owner: 'Ravi Patel',
    flow: 'Checkout / Payment',
    tags: ['payment', 'error-handling'],
    lastRun: new Date('2024-01-15T09:45:00Z'),
    passRate: 87,
    coverage: 78,
    risk: 'critical',
    aiScore: 89,
  },
  {
    id: 'TC-1043',
    title: 'Successful payment redirects to confirmation',
    priority: 'P0',
    automation: 'automated',
    owner: 'Ravi Patel',
    flow: 'Checkout / Payment',
    tags: ['payment', 'happy-path'],
    lastRun: new Date('2024-01-15T09:48:00Z'),
    passRate: 95,
    coverage: 82,
    risk: 'critical',
    aiScore: 92,
  },
  {
    id: 'TC-1128',
    title: 'Archived user cannot checkout',
    priority: 'P1',
    automation: 'partial',
    owner: 'Elena Garcia',
    flow: 'Checkout / Confirmation',
    tags: ['checkout', 'permissions'],
    lastRun: new Date('2024-01-14T16:20:00Z'),
    passRate: 75,
    coverage: 45,
    risk: 'medium',
    aiScore: 77,
  },
  {
    id: 'TC-1201',
    title: 'Add item to cart from product page',
    priority: 'P0',
    automation: 'automated',
    owner: 'Elena Garcia',
    flow: 'Checkout / Add Item',
    tags: ['cart', 'happy-path'],
    lastRun: new Date('2024-01-15T11:00:00Z'),
    passRate: 99,
    coverage: 95,
    risk: 'high',
    aiScore: 98,
  },
  {
    id: 'TC-1202',
    title: 'Remove item from cart updates total',
    priority: 'P1',
    automation: 'automated',
    owner: 'Elena Garcia',
    flow: 'Checkout / Add Item',
    tags: ['cart', 'calculation'],
    lastRun: new Date('2024-01-15T11:05:00Z'),
    passRate: 96,
    coverage: 88,
    risk: 'medium',
    aiScore: 91,
  },
  {
    id: 'TC-1305',
    title: 'Password reset email contains valid link',
    priority: 'P1',
    automation: 'automated',
    owner: 'Maya Chen',
    flow: 'Authentication / Forgot Password',
    tags: ['auth', 'email'],
    lastRun: new Date('2024-01-15T08:15:00Z'),
    passRate: 92,
    coverage: 70,
    risk: 'medium',
    aiScore: 85,
  },
];

export const mockExecutions = [
  {
    testName: 'TC-1042 Payment decline shows error banner',
    testId: 'TC-1042',
    flow: 'Checkout / Payment',
    browser: 'Chrome',
    environment: 'Staging',
    status: 'failed',
    duration: 48,
    retry: 1,
    aiConfidence: 87,
    owner: 'Ravi Patel',
    startedAt: new Date('2024-01-15T14:30:00Z'),
    errorMessage: 'Element not found: button[data-testid="pay-now"]',
    stackTrace: 'TimeoutError: Waiting for selector `button[data-testid="pay-now"]` failed',
  },
  {
    testName: 'TC-1001 Login with valid enterprise SSO user',
    testId: 'TC-1001',
    flow: 'Authentication / Login',
    browser: 'Chrome',
    environment: 'Staging',
    status: 'passed',
    duration: 12,
    retry: 0,
    aiConfidence: 98,
    owner: 'Maya Chen',
    startedAt: new Date('2024-01-15T14:28:00Z'),
  },
  {
    testName: 'TC-1201 Add item to cart from product page',
    testId: 'TC-1201',
    flow: 'Checkout / Add Item',
    browser: 'Firefox',
    environment: 'Production',
    status: 'passed',
    duration: 8,
    retry: 0,
    aiConfidence: 99,
    owner: 'Elena Garcia',
    startedAt: new Date('2024-01-15T14:25:00Z'),
  },
  {
    testName: 'TC-1128 Archived user cannot checkout',
    testId: 'TC-1128',
    flow: 'Checkout / Confirmation',
    browser: 'Chrome',
    environment: 'Staging',
    status: 'blocked',
    duration: 0,
    retry: 0,
    aiConfidence: 65,
    owner: 'Elena Garcia',
    startedAt: new Date('2024-01-15T14:20:00Z'),
    errorMessage: 'Test data setup failed: Could not create archived user',
  },
  {
    testName: 'TC-1043 Successful payment redirects to confirmation',
    testId: 'TC-1043',
    flow: 'Checkout / Payment',
    browser: 'Chrome',
    environment: 'Staging',
    status: 'running',
    duration: 0,
    retry: 0,
    aiConfidence: 91,
    owner: 'Ravi Patel',
    startedAt: new Date('2024-01-15T14:32:00Z'),
  },
  {
    testName: 'TC-1002 Login with invalid credentials shows error',
    testId: 'TC-1002',
    flow: 'Authentication / Login',
    browser: 'Safari',
    environment: 'Preview',
    status: 'passed',
    duration: 15,
    retry: 0,
    aiConfidence: 96,
    owner: 'Maya Chen',
    startedAt: new Date('2024-01-15T14:18:00Z'),
  },
  {
    testName: 'TC-1305 Password reset email contains valid link',
    testId: 'TC-1305',
    flow: 'Authentication / Forgot Password',
    browser: 'Chrome',
    environment: 'Staging',
    status: 'skipped',
    duration: 0,
    retry: 0,
    aiConfidence: 0,
    owner: 'Maya Chen',
    startedAt: new Date('2024-01-15T14:15:00Z'),
    errorMessage: 'Skipped: Email service unavailable',
  },
];

export const mockHealingSuggestions = [
  {
    issue: 'button[data-testid="pay-now"] no longer found',
    affectedTests: ['TC-1042', 'TC-1043', 'TC-1044'],
    currentLocator: 'button[data-testid="pay-now"]',
    suggestedLocator: "getByRole('button', { name: 'Pay now' })",
    confidence: 94,
    risk: 'low',
    owner: 'Healer Agent',
    status: 'pending',
    rootCause: 'Button testid was removed in commit abc123. Role-based locator is more stable.',
  },
  {
    issue: '#login-email selector ambiguous',
    affectedTests: ['TC-1001', 'TC-1002', 'TC-1003'],
    currentLocator: '#login-email',
    suggestedLocator: "getByLabel('Email address')",
    confidence: 89,
    risk: 'low',
    owner: 'Healer Agent',
    status: 'pending',
    rootCause: 'Multiple elements match #login-email. Label-based selector is unique.',
  },
  {
    issue: 'Cart total XPath fragile',
    affectedTests: ['TC-1201', 'TC-1202'],
    currentLocator: '/html/body/div[2]/main/div[3]/span[2]',
    suggestedLocator: "[data-testid='cart-total']",
    confidence: 78,
    risk: 'medium',
    owner: 'Healer Agent',
    status: 'pending',
    rootCause: 'Absolute XPath breaks on DOM structure changes. Test ID is recommended.',
  },
];

export const mockFlows = [
  {
    name: 'Login',
    module: 'Authentication',
    description: 'User authentication via email/password or SSO',
    risk: 'high',
    priority: 'P0',
    coverage: 88,
    automation: 95,
    relatedPages: ['Login Page', 'SSO Redirect', 'MFA Prompt'],
    dependencies: [],
  },
  {
    name: 'Registration',
    module: 'Authentication',
    description: 'New user account creation flow',
    risk: 'high',
    priority: 'P0',
    coverage: 75,
    automation: 80,
    relatedPages: ['Registration Page', 'Email Verification', 'Profile Setup'],
    dependencies: [],
  },
  {
    name: 'Forgot Password',
    module: 'Authentication',
    description: 'Password reset via email link',
    risk: 'medium',
    priority: 'P1',
    coverage: 65,
    automation: 70,
    relatedPages: ['Forgot Password Page', 'Reset Link Page', 'New Password Page'],
    dependencies: ['Login'],
  },
  {
    name: 'Add Item',
    module: 'Checkout',
    description: 'Add products to shopping cart',
    risk: 'high',
    priority: 'P0',
    coverage: 92,
    automation: 98,
    relatedPages: ['Product Page', 'Cart Page', 'Quick Add Modal'],
    dependencies: ['Login'],
  },
  {
    name: 'Payment',
    module: 'Checkout',
    description: 'Process payment with various methods',
    risk: 'critical',
    priority: 'P0',
    coverage: 78,
    automation: 85,
    relatedPages: ['Payment Page', 'Card Entry', '3DS Verification'],
    dependencies: ['Add Item'],
  },
  {
    name: 'Confirmation',
    module: 'Checkout',
    description: 'Order confirmation and receipt',
    risk: 'medium',
    priority: 'P1',
    coverage: 82,
    automation: 90,
    relatedPages: ['Confirmation Page', 'Order Summary', 'Email Receipt'],
    dependencies: ['Payment'],
  },
];

export const mockFacts = [
  {
    text: 'A locked account cannot start checkout',
    category: 'business_rule',
    confidence: 96,
    source: 'Confluence: Checkout Requirements',
    createdBy: 'Context Manager Agent',
    aiGenerated: true,
    humanVerified: true,
    relatedObjects: ['TC-1128', 'Checkout / Add Item'],
  },
  {
    text: 'SSO login bypasses MFA for enterprise users',
    category: 'business_rule',
    confidence: 92,
    source: 'Jira: AUTH-445',
    createdBy: 'Context Manager Agent',
    aiGenerated: true,
    humanVerified: true,
    relatedObjects: ['TC-1001', 'Authentication / Login'],
  },
  {
    text: 'Payment timeout is 30 seconds before retry prompt',
    category: 'constraint',
    confidence: 88,
    source: 'API Documentation',
    createdBy: 'Ravi Patel',
    aiGenerated: false,
    humanVerified: true,
    relatedObjects: ['TC-1042', 'TC-1043', 'Checkout / Payment'],
  },
  {
    text: 'Cart maximum is 99 items per product',
    category: 'validation',
    confidence: 100,
    source: 'Product Spec v2.3',
    createdBy: 'Elena Garcia',
    aiGenerated: false,
    humanVerified: true,
    relatedObjects: ['TC-1201', 'TC-1202', 'Checkout / Add Item'],
  },
];

export const mockDashboardStats = {
  passed: 1284,
  passedChange: 8.2,
  failed: 37,
  failedChange: -12.4,
  blocked: 9,
  blockedChange: 2,
  running: 14,
  skipped: 23,
  duration: '2h 34m',
  aiConfidence: 91,
  aiConfidenceChange: 3,
  healingCount: 22,
  healingPending: 5,
};
