const state = { page: 'dashboard', selected: { type: 'Test Case', title: 'TC-1042 Payment decline shows banner', status: 'Failed', confidence: '87%' }, dark: true };
const pages = { dashboard:'Quality Command Center', executions:'Executions', run:'Execution #14 / Run #1', healer:'Healer', context:'Context Manager', flows:'Flows', facts:'Fact Database', actions:'Action Library', dom:'DOM Snapshots', data:'Data Setup', testcases:'Test Cases', coverage:'Coverage Analysis', settings:'Settings & Integrations' };
const kpis = [['Passed','1,284','+8.2%','good'],['Failed','37','-12.4%','bad'],['Blocked','9','+2','warn'],['Running','14','live','info'],['Skipped','42','-5','muted'],['Duration','46m','-11m','good'],['AI Confidence','91%','+3%','ai'],['Healing Count','22','5 pending','ai']];
const executions = [['TC-1042 Payment decline shows banner','Checkout / Payment','Chrome','Staging','Failed','48s','1','87%','Maya Chen'],['TC-1001 Enterprise SSO login','Authentication / Login','Edge','Preview','Passed','31s','0','94%','Ravi Patel'],['TC-1128 Archived user cannot checkout','Checkout / Confirmation','Firefox','Staging','Blocked','16s','0','77%','Elena Garcia'],['TC-1177 Apply promotion code','Checkout / Add Item','Safari','Production','Running','22s','0','89%','Noor Ahmed']];
const tests = [['TC-1001','Login with valid enterprise SSO user','P0','Automated','Ravi Patel','Authentication / Login','sso, smoke','12m ago','99%','94%','High','94'],['TC-1042','Payment decline shows banner','P0','Automated','Maya Chen','Checkout / Payment','payments','Failed','87%','82%','High','89'],['TC-1128','Archived user cannot checkout','P1','Partial','Elena Garcia','Checkout / Confirmation','users','2h ago','73%','42%','Medium','77']];
const healing = [['Pay Now button locator changed','12','button[data-testid="pay-now"]','getByRole(button, Pay now)','94%','Low','Maya Chen'],['Toast role renamed','7','.toast-success','getByText(Payment complete)','82%','Medium','Ravi Patel'],['Email input moved into shadow DOM','4','#email','locator(form).getByLabel(Email)','76%','Medium','Noor Ahmed']];
const integrations = ['GitHub','Jira','Zephyr','Confluence','Notion','Azure DevOps','GitLab','Bitbucket','Postman','Swagger','Playwright','Cypress','Selenium','REST APIs','GraphQL','Database'];
const nav = [{label:'Dashboard',id:'dashboard'},{label:'Agents',children:[{label:'Executor',id:'executions',children:['Executions','Execution #14','Run #1','Test Cases','Logs','Timeline','AI Reasoning','Screenshots','Videos','Network','Console','Performance'].map((label,i)=>({label,id:i>0&&i<3?'run':'executions'}))},{label:'Healer',id:'healer',children:['Healing Queue','Suggestions','Approved','Rejected','Learning'].map(label=>({label,id:'healer'}))},{label:'Context Manager',id:'context',children:['Sources','Clarifications','Requests','Fact Builder','Embeddings','Relationships'].map(label=>({label,id:'context'}))},{label:'Test Case Manager',id:'testcases',children:['Test Cases','Coverage Analysis','PRs','Reviews','Suggestions'].map(label=>({label,id:label==='Coverage Analysis'?'coverage':'testcases'}))}]},{label:'Context',id:'context'},{label:'Flows',id:'flows'},{label:'Facts',id:'facts'},{label:'Actions',id:'actions'},{label:'DOM',id:'dom'},{label:'Data Setup',id:'data'},{label:'Test Cases',id:'testcases'},{label:'Settings',id:'settings'}];
const icon = {Dashboard:'▦',Agents:'◉',Context:'◎',Flows:'⑂',Facts:'▤',Actions:'{}',DOM:'⌘','Data Setup':'◈','Test Cases':'☑',Settings:'⚙'};
function esc(s){return String(s).replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));}
function setPage(page){state.page=page; render();}
function select(type,title,status='Open',confidence='91%'){state.selected={type,title,status,confidence}; render();}
function app(){return `<header class="topbar"><div class="crumb">Workspace › ${pages[state.page]}</div><button class="global-search" onclick="document.body.classList.toggle('show-command')">⌕ Search everything <kbd>Ctrl K</kbd></button><button class="btn primary">▶ Run</button><button class="btn">🔔</button><button class="btn" onclick="toggleTheme()">${state.dark?'Light':'Dark'}</button><div class="avatar">MC</div></header><div class="workspace"><aside class="left-sidebar"><div class="brand">✦ QA Master Agent</div>${tree(nav)}<div class="pulse"><b>Agents online</b><span>⚡ Executor streaming</span><span>🛡 Healer learning</span><span>◈ Context synced</span></div></aside><main class="main-panel">${header()}${content()}</main>${inspector()}</div>${copilot()}${notifications()}${commandPalette()}`;}
function tree(items,level=0){return `<div class="tree-level">${items.map(item=>`<button class="tree-item" style="padding-left:${10+level*16}px" onclick="${item.id?`setPage('${item.id}')`:''}"><span>${item.children?'⌄':'›'}</span><span>${icon[item.label]||'•'}</span>${item.label}</button>${item.children?tree(item.children,level+1):''}`).join('')}</div>`;}
function header(){return `<section class="page-header"><div><p class="eyebrow">AI-native QA automation platform</p><h1>${pages[state.page]}</h1></div><div class="actions"><button class="btn">☰ Filter</button><button class="btn">↻ Sync</button><button class="btn primary">✦ ${state.page==='healer'?'Approve Selected':'Generate'}</button></div></section>`;}
function content(){return ({dashboard,executions,run,healer,context,flows,facts,actions,dom,data,testcases,coverage,settings})[state.page]();}
function dashboard(){return `<div class="stack">${kpiGrid()}<div class="grid two">${chart('Execution Trends')}${heatmap('Failure Heatmap')}</div><div class="grid three">${card('Recent Executions',mini(['Execution #14 failed 37 tests','Preview run currently executing','Nightly smoke passed 99%'],'executions'))}${card('Agent Activity',mini(['Healer proposed 5 fixes','Context Manager verified 28 facts','Executor streamed 1.2k events']))}${card('AI Insights',mini(['Checkout Payment coverage below target','SSO flow stable across browsers','Zephyr token expires soon']))}</div><div class="grid two">${card('Pending Clarifications',clarification())}${card('Knowledge Graph Preview',graph())}</div></div>`;}
function executions(){return `<div class="stack">${kpiGrid()}${toolbar(['Search','Environment','Browser','Tags','Status','Date'])}${table(['Test Name','Flow','Browser','Environment','Status','Duration','Retry','AI Confidence','Owner'],executionsData(), 'execution')}</div>`;}
function executionsData(){return executions;}
function testcases(){return `<div class="stack">${toolbar(['ID or title','Priority','Automation','Owner','Flow','Risk','AI Score'])}${table(['ID','Title','Priority','Automation','Owner','Flow','Tags','Last Run','Pass Rate','Coverage','Risk','AI Score'],tests,'test')}${card('Professional Editable Test Steps',table(['Step','Action','Expected','Data','Locator','Automation Method','Status','Comments'],[[1,'enterEmail()','Email appears','validUser.email','#email','Playwright','Automated','Stable'],[2,'enterPassword()','Password accepted','secret','#password','Playwright','Automated','Masked'],[3,'clickLogin()','Dashboard opens','n/a','role button','Playwright','Automated','Healed once']]))}</div>`;}
function run(){return `<div class="grid run-grid">${card('Timeline',`<ol class="timeline">${['Load checkout','Create user data','Enter card','Click Pay now','Assert decline banner'].map((x,i)=>`<li onclick="select('Step','${x}','${i===3?'Failed':'Passed'}','${i===3?'87%':'98%'}')"><span class="dot ${i===3?'bad':'good'}"></span><b>${x}</b><small>${i*11+4}s</small></li>`).join('')}</ol>`)}${card('Evidence Viewer',screenshot())}${card('AI Reasoning Trace',`<pre>[agent] observing DOM snapshot\n[executor] click Pay now\n[network] POST /payments -> 402\n[ai] likely product behavior changed: error banner text differs\n[healer] suggested resilient role locator</pre>`)}</div>`;}
function healer(){return `<div class="grid two"><div class="stack">${toolbar(['Confidence','Risk','Owner','Created','Affected tests'])}${table(['Issue','Affected Tests','Locator','Suggested Locator','Confidence','Risk','Owner'],healing,'healing')}</div>${card('Diff Viewer · Locator Comparison',`<div class="diff"><p class="remove">- button[data-testid="pay-now"]</p><p class="add">+ getByRole('button', { name: 'Pay now' })</p><p>Confidence 94% · blast radius 12 tests · risk low</p><button class="btn primary">Approve</button><button class="btn">Reject</button></div>`)}</div>`;}
function context(){return `<div class="stack"><div class="cards integrations">${integrations.map((name,i)=>`<button class="integration" onclick="select('Integration','${name}','${i===2?'Warning':'Connected'}','Synced')"><span class="big">◎</span><strong>${name}</strong><span class="pill ${i===2?'warn':'good'}">${i===2?'Warning':'Connected'}</span><small>Last sync ${i+8} min ago</small></button>`).join('')}</div><div class="grid two">${card('Clarification UI',clarification())}${card('Knowledge Graph',graph())}</div></div>`;}
function flows(){return `<div class="grid two">${card('Business Hierarchy',`<div class="tree-static">Flows<br>└ Module<br>&nbsp;&nbsp;├ Authentication<br>&nbsp;&nbsp;│ ├ Login<br>&nbsp;&nbsp;│ ├ Registration<br>&nbsp;&nbsp;│ └ Forgot Password<br>&nbsp;&nbsp;└ Checkout<br>&nbsp;&nbsp;&nbsp;&nbsp;├ Add Item<br>&nbsp;&nbsp;&nbsp;&nbsp;├ Payment<br>&nbsp;&nbsp;&nbsp;&nbsp;└ Confirmation</div>`)}${card('Login Flow',`<div class="stats"><span>Risk <b>High</b></span><span>Priority <b>P0</b></span><span>Coverage <b>88%</b></span><span>Automation <b>76%</b></span></div>${heatmap('Coverage Heatmap')}`)}</div>`;}
function facts(){return `<div class="stack">${toolbar(['Category','Confidence','Source','Verified','Related object'])}${table(['Fact','Category','Confidence','Source','Created By','Updated By','Related Objects','AI Generated','Human Verified'],[['A locked account cannot start checkout','Business Rule','96%','Confluence','Context Agent','Maya','Checkout, User','Yes','Yes'],['Payment decline must show retry CTA','Validation Rule','91%','Jira','Context Agent','Ravi','Payment','Yes','No']])}</div>`;}
function actions(){return `<div class="grid code-grid">${card('Action Tree',mini(['Login Page / clickLogin()','Login Page / enterEmail()','Checkout / clickPayNow()','Checkout / verifyToast()']))}${card('Monaco-style Source Code',`<pre>async function clickPayNow(page) {\n  await page.getByRole('button', { name: 'Pay now' }).click();\n  await expect(page.getByText('Processing')).toBeVisible();\n}</pre>`)}${card('AI Explanation','<p>Uses an accessible role locator for better stability and healing confidence. Usage count: 12 tests.</p>')}</div>`;}
function dom(){return `<div class="grid dom-grid">${card('Screenshot',screenshot())}${card('DOM Tree and Locator Tree',`<pre>main#checkout\n  form.payment\n    input[name=cardNumber]\n    button[role=button] "Pay now"</pre>`)}${card('Accessibility',mini(['Button has accessible name','Input missing description','Color contrast passes AA']))}</div>`;}
function data(){return `<div class="grid two">${card('Entity Data Builders',mini(['User / Create','User / Update','User / Delete','User / Archive','User / Deactivate']))}${card('Preview and Execution History',table(['Mode','Status','Last Execution'],[['UI','Supported','Passed 2h ago'],['API','Supported','Passed 12m ago'],['Database','Supported','Passed 1d ago'],['Fixture','Supported','Never']]))}</div>`;}
function coverage(){return `<div class="stack"><div class="grid three">${chart('Business Coverage')}${chart('Requirement Coverage')}${chart('Automation %')}</div>${table(['Area','Requirement','Current Coverage','Risk','Missing Tests','Recommended Action','AI Confidence'],[['Checkout Payment','Decline handling','42%','High','8','Generate tests','93%'],['Authentication','SSO login','94%','High','1','Link fact','88%']])}</div>`;}
function settings(){return context();}
function kpiGrid(){return `<div class="kpis">${kpis.map(k=>`<div class="kpi"><span>${k[0]}</span><strong>${k[1]}</strong><em class="${k[3]}">${k[2]}</em></div>`).join('')}</div>`;}
function toolbar(filters){return `<div class="toolbar">${filters.map(f=>`<button class="filter">${f}⌄</button>`).join('')}<button class="btn">Export</button><button class="btn">Saved view</button></div>`;}
function table(headers,rows,type=''){return `<div class="tablewrap"><table><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr onclick="${rowSelect(type,r)}">${r.map(c=>`<td>${cell(c)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;}
function rowSelect(type,r){if(type==='execution')return `select('Test Case','${esc(r[0])}','${r[4]}','${r[7]}')`; if(type==='test')return `select('Test Case','${r[0]} ${esc(r[1])}','${r[7]}','${r[11]}%')`; if(type==='healing')return `select('Healing Suggestion','${esc(r[0])}','${r[5]}','${r[4]}')`; return '';}
function cell(value){const s=esc(value); const cls=s==='Failed'?'bad':s==='Passed'||s==='Connected'||s==='Automated'?'good':s==='Blocked'||s==='Warning'?'warn':s==='Running'?'info':''; return cls?`<span class="pill ${cls}">${s}</span>`:s;}
function card(title,body){return `<section class="card"><h3>${title}</h3>${body}</section>`;}
function chart(title){return card(title,`<div class="chart">${[35,54,42,70,58,86,74,92].map(h=>`<span style="height:${h}%"></span>`).join('')}</div>`);}
function heatmap(title){return card(title,`<div class="heat">${Array.from({length:35},(_,i)=>`<span class="${['a','b','c','d'][i%4]}"></span>`).join('')}</div>`);}
function mini(items,page){return `<ul class="mini">${items.map(x=>`<li ${page?`onclick="setPage('${page}')"`:''}>✓ ${x}</li>`).join('')}</ul>`;}
function clarification(){return `<div class="chat"><p>🤖 I found multiple login flows. Which one should become the canonical flow?</p><div><button class="btn primary">Accept</button><button class="btn">Reject</button><button class="btn">Merge</button><button class="btn">Answer</button></div></div>`;}
function graph(){return `<div class="graph">${['Pages','Flows','Facts','Actions','Requirements'].map((n,i)=>`<span style="left:${20+i*18}%;top:${20+(i%2)*45}%">${n}</span>`).join('')}</div>`;}
function screenshot(){return `<div class="screenshot"><div class="browserbar"></div><div class="fakepage"><input placeholder="Card number"/><button>Pay now</button><span class="target"></span></div></div>`;}
function inspector(){const s=state.selected; return `<aside class="right-inspector"><div class="inspect-head"><div><p class="eyebrow">${s.type}</p><h2>${s.title}</h2></div><span>◧</span></div><div class="tabs"><button>Overview</button><button>Evidence</button><button>AI Analysis</button><button>Activity</button></div><div class="inspect-body"><div class="status ${s.status==='Failed'?'bad':s.status==='Warning'?'warn':'good'}">${s.status}</div><p>Confidence: <b>${s.confidence}</b></p>${mini(['Execution History','Logs','DOM Snapshot','Screenshots','Network','Console','Stacktrace','Suggested Fixes'])}${card('Suggested Fix','<p>Use accessible role selectors, update related action library, and open an AI PR for review.</p><button class="btn primary">Open PR</button>')}</div></aside>`;}
function copilot(){return `<button class="ai-copilot">✦ Ask AI</button>`;}
function notifications(){return `<div class="notification-center">🐞 Healing suggestion awaiting review</div>`;}
function commandPalette(){return `<div class="command-palette"><div><button onclick="document.body.classList.remove('show-command')">×</button><h2>Search everything</h2><input autofocus placeholder="Test cases, executions, pages, flows, facts, actions, DOM, agents, users..."/><p>Try: Explain this failure · Generate checkout tests · Find flaky tests</p></div></div>`;}
window.setPage=setPage; window.select=select; window.toggleTheme=()=>{state.dark=!state.dark; render();};
function render(){document.getElementById('app').className=`app-shell ${state.dark?'dark':'light'}`;document.getElementById('app').innerHTML=app();}
document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();document.body.classList.toggle('show-command');} if(e.key==='Escape')document.body.classList.remove('show-command');});
render();
